// این فایل از داده واقعی «برنامه روزانه تعمیرات نگهداشت خط تولید» ساخته شده است.
// هر تجهیز شامل لیست کامل آیتم‌های بازرسی با نوع فیلد (چشمی/دما/آمپر/ولتاژ/ارتعاش) و توضیح تفصیلی است.
// توضیح تفصیلی هر آیتم برای نمایش در صفحه راهنما استفاده می‌شود (نه در خود فرم اصلی).

export const EQUIPMENT_CHECKLISTS = [
  {
    code: '1',
    name: "هاپر",
    inspectionFrequencyDays: 1,
    items: [
      {
        code: '1-1-1',
        category: "موتور ویبره",
        text: "بررسی وزنه و تعادل :",
        inspectionMethod: "بررسی چشمی هم راستا بودن و لرزش نامنظم",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی وزن و تعادل :\nبررسی چشمی اینکه آیا موتورهای ویبره با هم هم‌گام هستند یا یکی از آن‌ها صدای متفاوت یا لرزش نامنظم دارد",
      },
      {
        code: '1-1-2',
        category: "موتور ویبره",
        text: "وضعیت اتصالات پایه :",
        inspectionMethod: "شل بودن پیچ ها و واشر",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت اتصالات پایه : \nموتورهای ویبره با شدت زیاد به بدنه هاپر ضربه می‌زنند. بررسی کنید که پیچ‌های نگهدارنده موتور ویبره شل نشده باشند (این پیچ‌ها باید حتماً با واشر فنری یا مهره قفل‌کننده  بسته شده باشند",
      },
      {
        code: '1-1-3',
        category: "موتور ویبره",
        text: "بررسی سلامت پایه یا فنرهای ویبره :",
        inspectionMethod: "دچار تغییر شکل نشده باشند",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی سلامت پایه یا فنرهای ویبره : \nاگر موتورهای ویبره روی فنر یا پد لاستیکی سوار شده‌اند، بررسی کنید که پدها پاره نشده باشند یا فنرها دچار تغییر شکل نشوند.",
      },
      {
        code: '1-1-4',
        category: "موتور ویبره",
        text: "صدای برخورد فلز:",
        inspectionMethod: "صدای فلز به فلز که نشانه شل شدن اتصالات هست",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای برخورد فلز:\n شنیدن صدای برخورد فلز به فلز  که نشان‌دهنده شل شدن یکی از اتصالات موتور به بدنه هاپر است.",
      },
      {
        code: '1-1-5',
        category: "موتور ویبره",
        text: "دمای موتور ویبره:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "دمای موتور ویبره: \nموتورهای ویبره معمولاً گرم‌تر از موتورهای معمولی هستند، اما داغ شدن بیش از حد نشانه خرابی رولور  یا گیر کردن ذرات داخل آن است.",
      },
      {
        code: '1-2-1',
        category: "گیربکس",
        text: "سطح و سلامت روغن :",
        inspectionMethod: "چک چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح و سلامت روغن :",
      },
      {
        code: '1-2-2',
        category: "گیربکس",
        text: "بررسی نشتی روغن :",
        inspectionMethod: "چک کردن اطراف آب بندها",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی وزن و تعادل :\nبررسی چشمی اینکه آیا موتورهای ویبره با هم هم‌گام هستند یا یکی از آن‌ها صدای متفاوت یا لرزش نامنظم دارد",
      },
      {
        code: '1-2-3',
        category: "گیربکس",
        text: "صدای چرخ‌دنده‌ها:",
        inspectionMethod: "صدای زوزه نشانه عدم روغن کافی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای برخورد فلز:\n شنیدن صدای برخورد فلز به فلز  که نشان‌دهنده شل شدن یکی از اتصالات موتور به بدنه هاپر است.",
      },
      {
        code: '1-2-4',
        category: "گیربکس",
        text: "بررسی خالی بودن کناره های الکترموتور فیدر از سنگ",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی خالی بودن کناره های الکترموتور فیدر از سنگ",
      },
      {
        code: '1-2-5',
        category: "گیربکس",
        text: "بررسی نشت روغن دینام",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی وزن و تعادل :\nبررسی چشمی اینکه آیا موتورهای ویبره با هم هم‌گام هستند یا یکی از آن‌ها صدای متفاوت یا لرزش نامنظم دارد",
      },
      {
        code: '1-2-6',
        category: "گیربکس",
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی :",
        inspectionMethod: "با آمپر سنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "چک‌لیست روزانه موتور ویبره",
      },
    ],
  },
  {
    code: '2',
    name: "نوار نقاله مادر",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '2-1',
        category: null,
        text: "بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.",
      },
      {
        code: '2-2',
        category: null,
        text: "بررسی پارگی نوار",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی پارگی نوار",
      },
      {
        code: '2-3-1',
        category: "بررسی الکتروموتور",
        text: "بررسی دما ی الکتروموتور:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "بررسی دما ی الکتروموتور:\n(داغ شدن بیش از حد معمول معمولاً نشانه بار بیش از حد، خرابی بلبرینگ‌ها یا کمبود تهویه است.)",
      },
      {
        code: '2-3-2',
        category: "بررسی الکتروموتور",
        text: "بررسی صدا و لرزش الکتروموتور:",
        inspectionMethod: "گوش دادن صدا زوزه، خش خش و لرزش غیرعادی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی صدا و لرزش الکتروموتور:\n (زوزه نشانه مشکلات در بلبرینگ یا گیربکس -تق‌تق یا ضربه نشانه خرابی در بخش کوپلینگ یا اتصال موتور به نوار نقاله- صدای خش‌خش: نشانه ورود گرد و غبار یا ذرات معدنی به داخل بدنه موتور-لرزش غیرعادی: اگر موتور یا پایه آن می‌لرزد، احتمالاً پیچ‌های پایه شل شده‌اند یا محور موتور دچار انحراف  شده است)",
      },
      {
        code: '2-3-3',
        category: "بررسی الکتروموتور",
        text: "بازدید از پایه های الکتروموتور",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بازدید از پایه های الکتروموتور",
      },
      {
        code: '2-3-4',
        category: "بررسی الکتروموتور",
        text: "فن خنک کننده الکتروموتور",
        inspectionMethod: "تمیز بودن پره ها از گرد و غبار",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "فن خنک کننده:\nتمیزی پره‌های فن خنک‌کننده الکتروموتور که گرد و غبار حاصل از فرآوری  می‌تواند روی پره‌های فن موتور را بنشیند و جلوی خنک شدن را بگیرد. حتماً چک کنید که پره‌ها مسدود نشده باشند.",
      },
      {
        code: '2-3-5',
        category: "بررسی الکتروموتور",
        text: "وضعیت کابل‌های الکتروموتور",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت کابل‌ها: \nبررسی کنید که کابل‌های برق موتور بر اثر لرزش نوار نقاله، آسیب ندیده یا از ترمینال‌ها شل نشده باشند.",
      },
      {
        code: '2-4',
        category: null,
        text: "انحراف نوار :",
        inspectionMethod: "چشمی از بالا",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "انحراف نوار :\n(اگر نوار به یک سمت متمایل شده باشد، فشار غیرعادی به بلبرینگ‌های موتور و رولیک‌ها وارد می‌شود و باعث می‌شود موتور زودتر از موعد داغ کند و بسوزد)",
      },
      {
        code: '2-5',
        category: null,
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :برای شناسایی افت کارایی یا نیم‌سوز شدن(اگر آمپر موتور ناگهان بالا رفته است، یعنی یا نوار نقاله گیر کرده، یا بار مواد روی نوار خیلی زیاد است، و یا موتور در حال سوختن (نیم‌سوز شدن) است)",
      },
    ],
  },
  {
    code: '3',
    name: "گریزلی",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '3-1',
        category: null,
        text: "بررسی صفحه فلزی شیبدار از لحاظ سالم بودن جوش ها",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی صفحه فلزی شیبدار از لحاظ سالم بودن جوش های کناره",
      },
      {
        code: '3-2',
        category: null,
        text: "بررسی جوشهای توری",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای توری ترومل",
      },
      {
        code: '3-3-1',
        category: "بررسی الکتروموتور:",
        text: "بررسی دمای بدنه، یاتاقان جلو و عقب  الکتروموتور:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "بررسی دمای بدنه، یاتاقان جلو و عقب و باکس ترمینال الکتروموتور:\n(اگر دما نسبت به حالت عادی ناگهانی بالا رفت، علامت بار اضافه، گیر مکانیکی، مشکل بلبرینگ یا بدی تهویه است)",
      },
      {
        code: '3-3-2',
        category: "بررسی الکتروموتور:",
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):\n برای شناسایی افت کارایی یا نیم‌سوز شدن(آمپر هر سه فاز را کنترل کنید اختلاف زیاد بین فازها یا آمپر بالاتر از نرمال یعنی بار اضافی، مشکل در سیم پیچ گیرمکانیکی و ضعف برق ورودی)",
      },
      {
        code: '3-3-3',
        category: "بررسی الکتروموتور:",
        text: "وضعیت ظاهری الکتروموتور:",
        inspectionMethod: "عاری از گل و لای، ترک و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت ظاهری الکتروموتور:\n گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
      },
      {
        code: '3-3-4',
        category: "بررسی الکتروموتور:",
        text: "فن خنک‌کننده الکتروموتور :",
        inspectionMethod: "عاری از گل و لای، ترک و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "فن خنک‌کننده الکتروموتور :\n(مسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند)",
      },
      {
        code: '3-3-5',
        category: "بررسی الکتروموتور:",
        text: "پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.",
        inspectionMethod: "با آچار",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.",
      },
      {
        code: '3-3-6',
        category: "بررسی الکتروموتور:",
        text: "بوی غیرعادی الکتروموتور :",
        inspectionMethod: "اعم از سوختگی ، بوی لاک و بوی روغن سوخته",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بوی غیرعادی الکتروموتور اعم از سوختگی ، بوی لاک و بوی روغن سوخته علامتی جدی می باشد",
      },
      {
        code: '3-3-7',
        category: "بررسی الکتروموتور:",
        text: "وضعیت برق و ترمینال الکتروموتور:",
        inspectionMethod: "شل نبودن کابل، نبود جرقه و عدم خوردگی و سولفاته",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت برق و ترمینال الکتروموتور:\n (شل نبودن کابل، داغ نبودن ترمینال، نبود جرقه، سالم بودن ارت و عدم خوردگی و سولفاته)",
      },
      {
        code: '3-4',
        category: null,
        text: "بررسی کن نلسون در هنگام پایان ران",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی کن نلسون در هنگام پایان ران",
      },
      {
        code: '3-5',
        category: null,
        text: "بررسی تسمه ها از لحاظ پوسیدگی و پارگی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی تسمه ها از لحاظ پوسیدگی و پارگی",
      },
      {
        code: '3-6-1',
        category: "بررسی فنر:",
        text: "بررسی سلامت و وضعیت ظاهری فنرها  :",
        inspectionMethod: "عدم کنده شدن و خمیدگی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی سلامت و وضعیت ظاهری فنرها (مهم‌ترین مورد) تغییر شکل : \nبررسی اینکه آیا فنرها هنوز حالت استاندارد خود را دارند یا به دلیل بار بیش از حد، “کنده” یا “خمیده” شده‌اند.",
      },
      {
        code: '3-6-2',
        category: "بررسی فنر:",
        text: "شکستگی یا ترک:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "شکستگی یا ترک: \nبررسی دقیق ۸ عدد فنر برای یافتن هرگونه ترک یا شکستگی در بدنه فنر",
      },
      {
        code: '3-6-3',
        category: "بررسی فنر:",
        text: "تراز بودن ارتفاع فنرها:",
        inspectionMethod: "لرزش غیرعادی درصورت بار اضافی در یکطرف",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "تراز بودن ارتفاع:\n اگر یکی از فنرها بیش از بقیه فشرده شده باشد، یعنی بار روی گریزلی نامتقارن است (مثلاً مواد یک سمت گریزلی بیشتر از سمت دیگر می‌ریزد). این موضوع باعث لرزش غیرعادی و آسیب به شفت می‌شود.",
      },
      {
        code: '3-6-4',
        category: "بررسی فنر:",
        text: "بررسی پیچ‌ها و مهره‌های اتصال فنر به شاسی:",
        inspectionMethod: "عدم شل بودن پیچ و مهره فنر",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی پیچ‌ها و مهره‌های اتصال فنر به شاسی(سفت بودن اتصالات: \nبررسی اینکه پیچ‌هایی که فنر را به شاسی یا به صفحه گریزلی متصل می‌کنند، بر اثر لرزش شل نشده باشند.-\nنشانه خطر: اگر پیچ‌ها شل باشند، فنر شروع به “ضربه‌زدن”  می‌کند که صدای بسیار آزاردهنده‌ای دارد و می‌تواند باعث شکستن پایه گریزلی شود.)",
      },
      {
        code: '3-6-5',
        category: "بررسی فنر:",
        text: "لرزش موتور:",
        inspectionMethod: "با ارتغاش سنج",
        fieldType: 'vibration',
        unit: null,
        threshold: null,
        detail: "لرزش موتور: \nاگر فنرها درست نباشند، لرزش گریزلی به موتور گیربکس منتقل شده و باعث خرابی بلبرینگ‌های موتور می‌شود.",
      },
      {
        code: '3-7',
        category: null,
        text: "دمای گیربکس:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "دمای گیربکس: \nچک کردن دمای گیربکس (همان‌طور که قبلاً گفته شد) برای اطمینان از اینکه لرزش‌های ناشی از خرابی فنرها به گیربکس آسیب نزده است.",
      },
      {
        code: '3-8',
        category: null,
        text: "بررسی نازل آب از لحاظ گرفتگی",
        inspectionMethod: "چشمی(عدم آبریزش )",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی نازل آب از لحاظ گرفتگی",
      },
      {
        code: '3-9',
        category: null,
        text: "بررسی  جوشهای شوتی باطله",
        inspectionMethod: "چشمی(عدم آبریزش )",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی  جوشهای شوتی باطله",
      },
      {
        code: '3-10',
        category: null,
        text: "بررسی جوشهای شوتی مواد معدنی",
        inspectionMethod: "چشمی(عدم آبریزش )",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای شوتی مواد معدنی",
      },
      {
        code: '3-11',
        category: null,
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (18 کیلووات ):",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتور اصلی (18 کیلووات ) برای شناسایی افت کارایی یا نیم‌سوز شدن",
      },
    ],
  },
  {
    code: '4',
    name: "ترومل",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '4-1',
        category: null,
        text: "صدای چرخش و یکنواختی حرکت:",
        inspectionMethod: "با گوش دادن عدم تق تق، کوبش، و لرزش ضربه ای",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای چرخش و یکنواختی حرکت:\nترومل باید نرم و یکنواخت بچرخد، صدای غیرعادی مثل تق تق ، کوبش ، سایش فلز و لرزش ضربه ای باید فورا بررسی شود زیرا می تواند خرابی رولر یا تکیه گاه باشد یا کج شدن بدنه و یا  گیر کردن سنگ یا توده مواد داخل استوانه باشد",
      },
      {
        code: '4-2',
        category: null,
        text: "اطمینان از عدم گرفتگی  سوراخ‌ها برای شستشوی  نازل‌های آبپاش :",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی نازل‌های آبپاش :\nاطمینان از گرفتگی نداشتن سوراخ‌ها برای شستشوی بهینه",
      },
      {
        code: '4-3',
        category: null,
        text: "بازرسی زنجیر دوبل همیشه باید کمی روغنی باشد",
        inspectionMethod: "اطمینان از روغن‌کاری کافی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بازرسی زنجیر دوبل :\nاطمینان از روغن‌کاری کافی اگر زنجیر خشک، شل یا ضربه‌زننده باشد، هم عمر زنجیر کم می‌شود هم به گیربکس فشار می‌آید",
      },
      {
        code: '4-4',
        category: null,
        text: "بررسی یاتاقان‌ها:",
        inspectionMethod: "دما ، صدا، لقی غیر عادی و روغن ریزی و گریس ریزی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی یاتاقان‌ها:\nدما ، صدا، لقی غیر عادی و روغن ریزی و گریس ریزی",
      },
      {
        code: '4-5',
        category: null,
        text: "بررسی وضعیت پوشش تفلون  :",
        inspectionMethod: "چشمی پوشش تفلون سالم باشد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی وضعیت پوشش تفلون (حیاتی‌ترین مورد) :\nبررسی ظاهری برای اطمینان از اینکه پوشش تفلون نشده یا کنده شده باشد، اگر تفلون پوشش‌دهی خود را از دست بدهد و زنجیر مستقیماً با بدنه فلزی توپی برخورد کند صدای بسیار شدیدی ایجاد می‌شود زنجیر به سرعت دندانه می‌خورد و پاره می‌شود و دندانه خورشیدی نیز خورده میشود",
      },
      {
        code: '4-7',
        category: null,
        text: "هم‌راستایی  زنجیر و توپی:",
        inspectionMethod: "عدم ضربه زدن زنجیر به توپی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "هم‌راستایی  زنجیر و توپی:\nاگر زنجیر در یکی از بخش‌های مسیر خود صدا می‌دهد یا به سمت دیواره توپی برخورد می‌کند، یعنی تراز بودن  از بین رفته است.",
      },
      {
        code: '4-8',
        category: null,
        text: "کشیدگی و سلامت زنجیر :",
        inspectionMethod: "با دست شل یا سفت بودن زنجیر چک شود",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "کشیدگی و سلامت زنجیر :\nبررسی میزان شل بودن زنجیراگر زنجیر خیلی شل باشد: در هنگام حرکت، زنجیر روی دندانه‌های توپی پرش می‌کند  که باعث ضربه به موتور و شکستن دندانه‌ها می‌شود و اگر زنجیر خیلی سفت باشد: فشار غیرعادی به بلبرینگ‌های موتور و یاتاقان‌های توپی وارد می‌شود و باعث داغ شدن سریع آن‌ها می‌گردد.",
      },
      {
        code: '4-9',
        category: null,
        text: "روغن کاری و گریس کاری زنجیر همیشه باید کمی روغنی باشد",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "زنجیر باید همیشه دارای لایه نازکی از روغن یا گریس مخصوص زنجیر باشد",
      },
      {
        code: '4-10-1',
        category: "بررسی الکتروموتور 15 کیلو وات :",
        text: "بررسی الکتروموتورها از لحاظ روغن ریزی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی الکتروموتورها از لحاظ روغن ریزی",
      },
      {
        code: '4-10-2',
        category: "بررسی الکتروموتور 15 کیلو وات :",
        text: "بررسی دمای بدنه، یاتاقان جلو و عقب الکتروموتور",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "دمای بدنه : \nبا استفاده از تف (در صورت مجاز بودن) یا ترجیحاً با یک ترمومتر لیزری، دمای کاسه بلبرینگ را چک کنید. دمای غیرعادی نشان‌دهنده اصطکاک زیاد یا نبود روان‌کاری است.",
      },
      {
        code: '4-10-3',
        category: "بررسی الکتروموتور 15 کیلو وات :",
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات )",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتوراصلی (۱۵ کیلووات ) برای شناسایی افت کارایی یا نیم‌سوز شدن",
      },
      {
        code: '4-10-4',
        category: "بررسی الکتروموتور 15 کیلو وات :",
        text: "وضعیت ظاهری الکتروموتور",
        inspectionMethod: "عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت ظاهری الکتروموتور گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
      },
      {
        code: '4-10-5',
        category: "بررسی الکتروموتور 15 کیلو وات :",
        text: "فن خنک‌کننده الکتروموتور",
        inspectionMethod: "عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "فن خنک‌کننده الکتروموتور (مسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند)",
      },
      {
        code: '4-11-1',
        category: "بررسی شفت ترومل:",
        text: "دمای بدنه :",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "دمای بدنه : \nبا استفاده از تف (در صورت مجاز بودن) یا ترجیحاً با یک ترمومتر لیزری، دمای کاسه بلبرینگ را چک کنید. دمای غیرعادی نشان‌دهنده اصطکاک زیاد یا نبود روان‌کاری است.",
      },
      {
        code: '4-11-2',
        category: "بررسی شفت ترومل:",
        text: "صدای غیرعادی :",
        inspectionMethod: "صدای زوزه و تق تق نداشته باشد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای غیرعادی : \nگوش دادن به صدای چرخش. هرگونه صدای «زوزه»  یا «تق‌تق»  نشان‌دهنده آسیب به رینگ‌های بلبرینگ یا عدم تراز شفت است.",
      },
      {
        code: '4-11-3',
        category: "بررسی شفت ترومل:",
        text: "لرزش محسوس :",
        inspectionMethod: "با ارتعاش سنج",
        fieldType: 'vibration',
        unit: null,
        threshold: null,
        detail: "لرزش محسوس : \nبررسی  که آیا لرزش دستگاه در حد نرمال است یا لرزش‌های ضربه‌ای شنیده می‌شود.",
      },
      {
        code: '4-11-4',
        category: "بررسی شفت ترومل:",
        text: "وضعیت روغن/گریس:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت روغن/گریس: \nاگر سیستم روغن‌کاری  دستی دارد، چک کنید که آیا نشتی از آب‌بند (Seal) کاسه بلبرینگ وجود دارد یا خیر",
      },
      {
        code: '4-11-5',
        category: "بررسی شفت ترومل:",
        text: "بررسی انحراف :",
        inspectionMethod: "عدم نوسان زیاد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی انحراف :\n با چشم (در صورت امکان) یا سنسور، چک شود که آیا شفت در حین چرخش دارای لرزش‌های جانبی یا نوسان شدید است؟ (نوسان زیاد یعنی شفت کج شده یا بلبرینگ‌ها فاصله گرفته‌اند).",
      },
      {
        code: '4-11-6',
        category: "بررسی شفت ترومل:",
        text: "بررسی  پایه های نگهدارنده شفت ترومل",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی  پایه های نگهدارنده شفت ترومل",
      },
      {
        code: '4-12',
        category: null,
        text: "بررسی جوشهای شوتی ترومل",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای شوتی ترومل",
      },
      {
        code: '4-13',
        category: null,
        text: "بررسی توری ترومل از لحاظ پارگی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی توری ترومل از لحاظ پارگی",
      },
      {
        code: '4-14',
        category: null,
        text: "بررسی توری ترومل از لحاظ گرفتگی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی توری ترومل از لحاظ گرفتگی",
      },
      {
        code: '4-15',
        category: null,
        text: "بررسی تسمه ها و پیچ و مهره های آن",
        inspectionMethod: "لمسی",
        fieldType: 'tactile',
        unit: null,
        threshold: null,
        detail: "بررسی تسمه ها و پیچ و مهره های آن",
      },
      {
        code: '4-16',
        category: null,
        text: "تست آمپراژ (آمپرسنجی)  موتوراصلی (۱۵ کیلووات )",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتوراصلی (۱۵ کیلووات ) برای شناسایی افت کارایی یا نیم‌سوز شدن",
      },
    ],
  },
  {
    code: '5',
    name: "سرند لرزان",
    inspectionFrequencyDays: 1,
    items: [
      {
        code: '5-1',
        category: null,
        text: "بررسی پا اردکی ها از لحاظ گرفتگی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی پا اردکی ها از لحاظ گرفتگی",
      },
      {
        code: '5-2',
        category: null,
        text: "بررسی کاشی های از لحاظ گرفتگی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی کاشی های از لحاظ گرفتگی",
      },
      {
        code: '5-3',
        category: null,
        text: "بررسی پیچ و مهره های کاشی ها",
        inspectionMethod: "لمسی",
        fieldType: 'tactile',
        unit: null,
        threshold: null,
        detail: "بررسی پیچ و مهره های کاشی ها",
      },
      {
        code: '5-4',
        category: null,
        text: "بررسی عدم روغن ریزی موتور ویبره",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی عدم روغن ریزی موتور ویبره",
      },
      {
        code: '5-5',
        category: null,
        text: "بررسی تراز بودن موتورها با میل گاردن(افقی و عمودی):",
        inspectionMethod: "فاصله دو طرف کوپلینگ را اندازه بگیرید یکسان باشد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی تراز بودن موتورها با میل گاردن:\nاگر موتورها به خوبی تراز نباشند، میل‌گاردن مثل یک میله کج شروع به ضربه زدن به شفت موتورها می‌کند و در کمتر از یک هفته بلبرینگ‌های موتور را خرد می‌کند",
      },
      {
        code: '5-6',
        category: null,
        text: "کنترل زاویه میل گاردن:",
        inspectionMethod: "بین 2 تا 5 درجه باید باشد",
        fieldType: 'visual',
        unit: null,
        threshold: "بین 2 تا 5 درجه باید باشد",
        detail: "سلامت میل‌گاردن:\nچون لرزش شدید است، هزارخاری‌ها یا کوپلینگ‌های میل‌گاردن مستعد ساییدگی هستند. روزانه چک کنید که در محل اتصال میل‌گاردن به موتور، لقی  ایجاد نشده باشد",
      },
      {
        code: '5-7',
        category: null,
        text: "پیچ‌های پایه موتور ویبره:",
        inspectionMethod: "اطمینان از سفت بودن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سفت بودن پیچ‌های پایه موتور ویبره:\nاگر پیچ‌های پایه حتی کمی لق شوند، لرزش موتور باعث ضربه زدن به ورق فولادی زیر آن می‌شود که نتیجه‌اش شکستن شاسی یا ایجاد ترک در بدنه هاپر/سرند است.",
      },
      {
        code: '5-8',
        category: null,
        text: "تست آمپراژ (آمپرسنجی)  موتورها :",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتورها برای شناسایی افت کارایی یا نیم‌سوز شدن(اگر وزنه‌های لنگ  داخل موتور ویبره بر اثر لرزش جابجا شوند یا بلبرینگ‌ها نیم‌سوز شوند، آمپر موتور ناگهان بالا می‌رود.)",
      },
      {
        code: '5-9',
        category: null,
        text: "صدای بلبرینگ‌های موتور ویبره:",
        inspectionMethod: "صدای خشن نداشته باشد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای بلبرینگ‌های موتور ویبره:\nموتورهای ویبره تحت فشار “نیروی گریز از مرکز” شدیدی هستند. خرابی بلبرینگ در این موتورها معمولاً با صدای “هوم” خشن یا سوتِ ریز شروع می‌شود.استفاده از یک پیچ‌گوشتی بلند به عنوان “گوشی پزشکی” (دسته پیچ‌گوشتی را روی گوش و نوک آن را روی بدنه موتور بگذارید) تا صدای غیرعادی بلبرینگ را بهتر بشنوید)",
      },
      {
        code: '5-10',
        category: null,
        text: "داغ کردن بدنه موتور ویبره :",
        inspectionMethod: "با دماسنج لیزری",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: null,
        detail: "داغ کردن بدنه موتور ویبره :\nبه دلیل نداشتن فن خنک‌کننده ، گرم می‌شوند. اما اگر دمای آن به قدری بالاست که دست را می‌سوزاند، یعنی موتور بیش از حد بار دارد یا بلبرینگ‌ها در حال گیرپاژ هستند",
      },
      {
        code: '5-11',
        category: null,
        text: "بررسی ارتعاش وزنه‌ها:",
        inspectionMethod: "با ارتعاش سنج",
        fieldType: 'vibration',
        unit: null,
        threshold: null,
        detail: "بررسی محافظ وزنه‌ها:\nارتعاش زیاد باعث شل شدن پیچ‌های  درپوش‌ها می‌شود. اگر درپوش بیفتد، وزنه‌های لنگ بیرون پرتاب می‌شوند که بسیار خطرناک است.",
      },
      {
        code: '5-12',
        category: null,
        text: "سلامت میل‌گاردن:",
        inspectionMethod: "عدم داشتن لقی و انحراف",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سلامت میل‌گاردن:\nچون لرزش شدید است، هزارخاری‌ها یا کوپلینگ‌های میل‌گاردن مستعد ساییدگی هستند. روزانه چک کنید که در محل اتصال میل‌گاردن به موتور، لقی  ایجاد نشده باشد",
      },
    ],
  },
  {
    code: '6',
    name: "پمپ اسلاری",
    inspectionFrequencyDays: 1,
    items: [
      {
        code: '6-1-1',
        category: "سیستم خنک‌کننده دیزل",
        text: "سطح مایع خنک‌کننده :",
        inspectionMethod: "چک آب رادیاتور",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح مایع خنک‌کننده : \nدر مخزن رادیاتور، مطمئن شوید که سطح مایع خنک‌کننده در حد نرمال است.",
      },
      {
        code: '6-1-2',
        category: "سیستم خنک‌کننده دیزل",
        text: "وضعیت شیلنگ‌ها و اتصالات :",
        inspectionMethod: "عدم وجود نشتی، ترک یا ورم",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت شیلنگ‌ها و اتصالات : \nاز نظر وجود نشتی، ترک‌خوردگی، یا ورم‌کردگی شیلنگ‌ها و همچنین سفتی اتصالات.",
      },
      {
        code: '6-1-3',
        category: "سیستم خنک‌کننده دیزل",
        text: "عملکرد فن خنک‌کننده :",
        inspectionMethod: "مطمئن شدن فن بدون صدای اضافی و با قدرت کافی می‌چرخد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "عملکرد فن خنک‌کننده : \nمطمئن شوید فن بدون صدای اضافی و با قدرت کافی می‌چرخد.",
      },
      {
        code: '6-2-1',
        category: "سیستم روان‌کاری دیزل",
        text: "سطح روغن موتور :",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح روغن موتور : \nبا گیج روغن، سطح آن را چک کنید. سطح باید بین حداقل و حداکثر علامت‌گذاری شده باشد.",
      },
      {
        code: '6-2-2',
        category: "سیستم روان‌کاری دیزل",
        text: "وضعیت فیلتر روغن :",
        inspectionMethod: "عدم نشتی از فیلتر روغن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت فیلتر روغن : \nبررسی کنید که آیا نشتی از اطراف فیلتر روغن وجود دارد یا خیر",
      },
      {
        code: '6-2-3',
        category: "سیستم روان‌کاری دیزل",
        text: "رنگ و بوی روغن:",
        inspectionMethod: "عدم رنگ شیری و سیاه",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "رنگ و بوی روغن: \nاگر امکانش هست، کمی روغن را بین انگشتان خود بمالید. رنگ غیرعادی (مثل شیری شدن که نشانه مخلوط شدن با آب است) یا بوی سوختگی نیاز به بررسی فوری دارد.",
      },
      {
        code: '6-2-4',
        category: "سیستم روان‌کاری دیزل",
        text: "بررسی عدم آب دهی سل مکانیکی پمپ اسلاری",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی عدم آب دهی سل مکانیکی پمپ اسلاری",
      },
      {
        code: '6-3-1',
        category: "سیستم سوخت‌رسانی دیزل",
        text: "سطح سوخت : بررسی مخزن سوخت",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح سوخت : بررسی مخزن سوخت",
      },
      {
        code: '6-3-2',
        category: "سیستم سوخت‌رسانی دیزل",
        text: "نشتی سوخت :",
        inspectionMethod: "از شیلنگ‌ها، اتصالات، پمپ گازوئیل، و اطراف انژکتورها",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشتی سوخت : \nاز شیلنگ‌ها، اتصالات، پمپ گازوئیل، و اطراف انژکتورها",
      },
      {
        code: '6-3-3',
        category: "سیستم سوخت‌رسانی دیزل",
        text: "نشتی اگزوز :",
        inspectionMethod: "عدم دیدن دود سیاه یا آبی که از منیفولد، لوله‌ها و اتصالات",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشتی اگزوز : \nاز منیفولد، لوله‌ها و اتصالات. دود سیاه یا آبی که از اگزوز خارج می‌شود، می‌تواند نشانه مشکل باشد.",
      },
      {
        code: '6-4-1',
        category: "سیستم کلاچ چرخ‌دنده‌ای",
        text: "نشت گریس/روغن:",
        inspectionMethod: "نشتی از محل کاسه نمدها نشانه خرابی آن‌هاست",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشت گریس/روغن: \n نشتی از محل کاسه نمدها (Seals) نشانه خرابی آن‌هاست.",
      },
      {
        code: '6-4-2',
        category: "سیستم کلاچ چرخ‌دنده‌ای",
        text: "صدای غیرعادی:",
        inspectionMethod: "عدم شنیدن صدای جیرجیر و تق تق",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای غیرعادی:\n در حین کار، به صداهای غیرعادی مثل «جیرجیر» یا «تق‌تق» گوش دهید که می‌تواند نشانه فرسودگی چرخ‌دنده‌ها یا عدم روان‌کاری باشد.",
      },
      {
        code: '6-4-3',
        category: "سیستم کلاچ چرخ‌دنده‌ای",
        text: "لرزش:",
        inspectionMethod: "ارتعاش سنج",
        fieldType: 'vibration',
        unit: null,
        threshold: null,
        detail: "لرزش: \nلرزش بیش از حد در ناحیه اتصال کلاچ، نشان‌دهنده عدم تراز یا خرابی دندانه‌های چرخ‌دنده است.",
      },
      {
        code: '6-5',
        category: null,
        text: "بررسی شل یا سفت بودن تسمه اسلاری",
        inspectionMethod: "با آچار",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "بررسی شل یا سفت بودن تسمه اسلاری",
      },
      {
        code: '6-6-1',
        category: "پمپ اسلاری:",
        text: "نشت از کاسه نمد پمپ :",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشت از کاسه نمد پمپ :\n این مهم‌ترین بخش پمپ است. هرگونه نشتی اسلاری از اطراف شفت پمپ نیاز به بررسی فوری دارد.",
      },
      {
        code: '6-6-2',
        category: "پمپ اسلاری:",
        text: "وضعیت روان‌کاری بلبرینگ پمپ:",
        inspectionMethod: "با آچار",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "وضعیت روان‌کاری بلبرینگ پمپ:\n اگر پمپ بلبرینگ جداگانه دارد، سطح گریس یا روغن آن را چک کنید.",
      },
      {
        code: '6-6-3',
        category: "پمپ اسلاری:",
        text: "دمای بدنه پمپ:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "دمای بدنه پمپ: \nبا دست (با احتیاط) یا تف، دمای بدنه پمپ را چک کنید. داغ شدن بیش از حد معمولاً نشانه بار زیاد یا خرابی بلبرینگ پمپ است.",
      },
      {
        code: '6-6-4',
        category: "پمپ اسلاری:",
        text: "سفتی پیچ‌ها:",
        inspectionMethod: "اطمینان از سفت بودن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سفتی پیچ‌ها:\n تمامی پیچ‌های اتصال دهنده دیزل به پمپ، و اجزای نصب شده بر روی شاسی را از نظر سفتی چک کنید",
      },
      {
        code: '6-6-5',
        category: "پمپ اسلاری:",
        text: "لوله های انتقال اسلاری:",
        inspectionMethod: "عدم وجود ترک، پارگی، یا بادکردگی، مخصوصاً در نقاط اتصال",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "لوله های انتقال اسلاری:\n از نظر وجود ترک، پارگی، یا بادکردگی، مخصوصاً در نقاط اتصال",
      },
    ],
  },
  {
    code: '7',
    name: "مقسم‌ها",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '7-1',
        category: null,
        text: "بررسی ورق داخل مخزن از لحاظ پخش دوغاب بصورت یکسان",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی ورق داخل مخزن از لحاظ پخش دوغاب بصورت یکسان",
      },
      {
        code: '7-2',
        category: null,
        text: "بررسی جوشهای مقسم",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای مقسم",
      },
      {
        code: '7-3',
        category: null,
        text: "بررسی جوشهای لوله های مقسم",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای لوله های مقسم",
      },
    ],
  },
  {
    code: '8',
    name: "نلسون",
    inspectionFrequencyDays: 1,
    items: [
      {
        code: '8-1-1',
        category: "الکتروموتورها",
        text: "بررسی الکتروموتورها از لحاظ روغن ریزی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی الکتروموتورها از لحاظ روغن ریزی",
      },
      {
        code: '8-1-2',
        category: "الکتروموتورها",
        text: "بررسی دمای بدنه، یاتاقان جلو و عقب الکتروموتور:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "بررسی دمای بدنه، یاتاقان جلو و عقب و باکس ترمینال الکتروموتور:\nاگر دما نسبت به حالت عادی ناگهانی بالا رفت، علامت بار اضافه، گیر مکانیکی، مشکل بلبرینگ یا بدی تهویه است",
      },
      {
        code: '8-1-3',
        category: "الکتروموتورها",
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):\n برای شناسایی افت کارایی یا نیم‌سوز شدن(آمپر هر سه فاز را کنترل کنید اختلاف زیاد بین فازها یا آمپر بالاتر از نرمال یعنی بار اضافی، مشکل در سیم پیچ گیرمکانیکی و ضعف برق ورودی",
      },
      {
        code: '8-1-4',
        category: "الکتروموتورها",
        text: "وضعیت ظاهری الکتروموتور:",
        inspectionMethod: "عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت ظاهری الکتروموتور:\n گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
      },
      {
        code: '8-1-5',
        category: "الکتروموتورها",
        text: "فن خنک‌کننده الکتروموتور :",
        inspectionMethod: "عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "فن خنک‌کننده الکتروموتور :\nمسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند",
      },
      {
        code: '8-1-6',
        category: "الکتروموتورها",
        text: "پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.",
        inspectionMethod: "با آچار",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.",
      },
      {
        code: '8-1-7',
        category: "الکتروموتورها",
        text: "بوی غیرعادی الکتروموتور:",
        inspectionMethod: "عدم وجود  سوختگی ، بوی لاک و بوی روغن سوخته",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بوی غیرعادی الکتروموتور:\n اعم از سوختگی ، بوی لاک و بوی روغن سوخته علامتی جدی می باشد",
      },
      {
        code: '8-1-8',
        category: "الکتروموتورها",
        text: "وضعیت برق و ترمینال الکتروموتور:",
        inspectionMethod: "شل نبودن کابل، نبود جرقه و عدم خوردگی و سولفاته",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت برق و ترمینال الکتروموتور:\n شل نبودن کابل، داغ نبودن ترمینال، نبود جرقه، سالم بودن ارت و عدم خوردگی و سولفاته",
      },
      {
        code: '8-2',
        category: null,
        text: "بررسی کن نلسون در هنگام پایان ران",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی کن نلسون در هنگام پایان ران",
      },
      {
        code: '8-3',
        category: null,
        text: "بررسی تسمه ها از لحاظ پوسیدگی و پارگی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی تسمه ها از لحاظ پوسیدگی و پارگی",
      },
    ],
  },
  {
    code: '9',
    name: "اسلایدباکس",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '9-1',
        category: null,
        text: "بررسی جوشهای باکس",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای باکس",
      },
      {
        code: '9-2',
        category: null,
        text: "بررسی خرابی چمن مصنوعی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی خرابی چمن مصنوعی",
      },
    ],
  },
  {
    code: '10',
    name: "اسپیرال",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '10-1-1',
        category: "گیبرکس",
        text: "بررسی دمای بدنه (مهم‌ترین فاکتور):",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "بررسی دمای بدنه (مهم‌ترین فاکتور):\n با دماسنج لیزری(  دمای گیربکس در حین کار باید در محدوده نرمال (معمولاً زیر ۷۰-۸۰ درجه سانتی‌گراد) باشد. اگر دمای گیربکس ناگهان بالا رفته است، یا روغن کم شده، یا بار بیش از حد به آن تحمیل می‌شود (تنش در اسپیرال)، یا بلبرینگ‌ها در حال گیرپاژ هستند.)",
      },
      {
        code: '10-1-2',
        category: "گیبرکس",
        text: "کنترل سطح روغن گیربکس (سطح‌سنج):",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "کنترل سطح روغن گیربکس (سطح‌سنج):\n سطح روغن نباید از خط نشان‌دهنده پایین‌تر برود. اگر سطح روغن کاهش یافته، بلافاصله باید محل نشت کاسه‌نمدها یا درزهای گیربکس پیدا شود",
      },
      {
        code: '10-1-3',
        category: "گیبرکس",
        text: "بررسی نشت روغن (نشتی‌گیری):",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی نشت روغن (نشتی‌گیری):\nچک کردن زیر گیربکس و دور شفت‌ها (محل خروجی شفت به اسپیرال)گیربکس‌های قورباغه‌ای به دلیل لرزش شدید، مستعد نشت از کاسه‌نمد  هستند. اگر روغن نشت کند، به سرعت سطح روغن پایین آمده و چرخ‌دنده‌ها درگیر خشکی می‌شوند.",
      },
      {
        code: '10-1-4',
        category: "گیبرکس",
        text: "شنوایی  گیربکس(آنالیز صدای غیرعادی):",
        inspectionMethod: "عدم صدای زوزه و تق تق",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "شنوایی  گیربکس(آنالیز صدای غیرعادی):\nگوش دادن به صدای گیربکس در حین کارصدای گیربکس باید یکنواخت باشد. شنیدن صدای “زوزه” شدید، “تق‌تق” یا صدای کوبش فلز با فلز، نشان‌دهنده خوردگی چرخ‌دنده‌ها  یا خرابی بلبرینگ‌های داخلی است",
      },
      {
        code: '10-1-5',
        category: "گیبرکس",
        text: "لرزش‌های غیرطبیعی گیربکس:",
        inspectionMethod: "با ارتعاش سنج",
        fieldType: 'vibration',
        unit: null,
        threshold: null,
        detail: "لرزش‌های غیرطبیعی گیربکس:\n با دست گذاشتن روی بدنه گیربکس لرزش باید در حد معمولِ کاری باشد. اگر لرزش شدید و غیرمعمول حس می‌کنید، ممکن است محور اسپیرال با گیربکس هم‌راستا نباشد (هم راستا بودن مشکل پیدا کرده است) که فشار مضاعف به شفت خروجی گیربکس وارد می‌کند.اتصال موتور ۱۵ کیلووات به گیربکس را چک کنید. چون موتور ارتعاش دارد، اگر کوپلینگ یا واسطه بین موتور و گیربکس شل شده باشد، “لقی” ایجاد شده و دندانه‌های گیربکس خیلی سریع مستهلک می‌شوند",
      },
      {
        code: '10-2-1',
        category: "الکتروموتور",
        text: "بررسی الکتروموتورها از لحاظ روغن ریزی",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی الکتروموتورها از لحاظ روغن ریزی",
      },
      {
        code: '10-2-2',
        category: "الکتروموتور",
        text: "بررسی دمای بدنه، یاتاقان جلو و عقب  الکتروموتور",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "الکتروموتور",
      },
      {
        code: '10-2-3',
        category: "الکتروموتور",
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ) :",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ) :\nبرای شناسایی افت کارایی یا نیم‌سوز شدن(آمپر هر سه فاز را کنترل کنید اختلاف زیاد بین فازها یا آمپر بالاتر از نرمال یعنی بار اضافی، مشکل در سیم پیچ گیرمکانیکی و ضعف برق ورودی",
      },
      {
        code: '10-2-4',
        category: "الکتروموتور",
        text: "وضعیت ظاهری الکتروموتور:",
        inspectionMethod: "عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت ظاهری الکتروموتور:\n گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
      },
      {
        code: '10-2-5',
        category: "الکتروموتور",
        text: "فن خنک‌کننده الکتروموتور :",
        inspectionMethod: "عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "فن خنک‌کننده الکتروموتور :\nمسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند",
      },
      {
        code: '10-2-6',
        category: "الکتروموتور",
        text: "پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.",
        inspectionMethod: "با آچار",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.",
      },
      {
        code: '10-2-7',
        category: "الکتروموتور",
        text: "بوی غیرعادی الکتروموتور:",
        inspectionMethod: "عدم سوختگی ، بوی لاک و بوی روغن سوخته",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بوی غیرعادی الکتروموتور:\n اعم از سوختگی ، بوی لاک و بوی روغن سوخته علامتی جدی می باشد",
      },
      {
        code: '10-2-8',
        category: "الکتروموتور",
        text: "وضعیت برق و ترمینال الکتروموتور:",
        inspectionMethod: "شل نبودن کابل، نبود جرقه و عدم خوردگی و سولفاته",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت برق و ترمینال الکتروموتور:\n شل نبودن کابل، داغ نبودن ترمینال، نبود جرقه، سالم بودن ارت و عدم خوردگی و سولفاته",
      },
      {
        code: '10-3',
        category: null,
        text: "بررسی جوشهای بدنه",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی جوشهای بدنه",
      },
    ],
  },
  {
    code: '11',
    name: "نوار نقاله ماسه",
    inspectionFrequencyDays: 7,
    items: [
      {
        code: '11-1',
        category: null,
        text: "بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.",
      },
      {
        code: '11-2',
        category: null,
        text: "بررسی پارگی نوار",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی پارگی نوار",
      },
      {
        code: '11-3-1',
        category: "بررسی الکتروموتور",
        text: "بررسی دما ی الکتروموتور:",
        inspectionMethod: "با دماسنج لیزری",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: null,
        detail: "بررسی دما ی الکتروموتور:\nداغ شدن بیش از حد معمول معمولاً نشانه بار بیش از حد، خرابی بلبرینگ‌ها یا کمبود تهویه است.",
      },
      {
        code: '11-3-2',
        category: "بررسی الکتروموتور",
        text: "بررسی صدا و لرزش الکتروموتور:",
        inspectionMethod: "عدم صدای زوزه و تق تق و لرزش بیش از حد",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بررسی صدا و لرزش الکتروموتور:\n زوزه نشانه مشکلات در بلبرینگ یا گیربکس -تق‌تق یا ضربه نشانه خرابی در بخش کوپلینگ یا اتصال موتور به نوار نقاله- صدای خش‌خش: نشانه ورود گرد و غبار یا ذرات معدنی به داخل بدنه موتور-لرزش غیرعادی: اگر موتور یا پایه آن می‌لرزد، احتمالاً پیچ‌های پایه شل شده‌اند یا محور موتور دچار انحراف  شده است",
      },
      {
        code: '11-3-3',
        category: "بررسی الکتروموتور",
        text: "بازدید از پایه های الکتروموتور",
        inspectionMethod: "اطمینان از سفت بودن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "بازدید از پایه های الکتروموتور",
      },
      {
        code: '11-3-4',
        category: "بررسی الکتروموتور",
        text: "فن خنک کننده:",
        inspectionMethod: "عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "فن خنک کننده:\nتمیزی پره‌های فن خنک‌کننده الکتروموتور که گرد و غبار حاصل از فرآوری  می‌تواند روی پره‌های فن موتور را بنشیند و جلوی خنک شدن را بگیرد. حتماً چک کنید که پره‌ها مسدود نشده باشند.",
      },
      {
        code: '11-4',
        category: null,
        text: "وضعیت کابل‌ها:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت کابل‌ها: \nبررسی کنید که کابل‌های برق موتور بر اثر لرزش نوار نقاله، آسیب ندیده یا از ترمینال‌ها شل نشده باشند.",
      },
      {
        code: '11-5',
        category: null,
        text: "انحراف نوار :",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "انحراف نوار :\n(اگر نوار به یک سمت متمایل شده باشد، فشار غیرعادی به بلبرینگ‌های موتور و رولیک‌ها وارد می‌شود و باعث می‌شود موتور زودتر از موعد داغ کند و بسوزد)",
      },
      {
        code: '11-6',
        category: null,
        text: "تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :",
        inspectionMethod: "با آمپرسنج",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :\nبرای شناسایی افت کارایی یا نیم‌سوز شدن(اگر آمپر موتور ناگهان بالا رفته است، یعنی یا نوار نقاله گیر کرده، یا بار مواد روی نوار خیلی زیاد است، و یا موتور در حال سوختن (نیم‌سوز شدن) است",
      },
    ],
  },
  {
    code: '12',
    name: "دیزل ژنراتور",
    inspectionFrequencyDays: 1,
    items: [
      {
        code: '12-1-1',
        category: "وضعیت ظاهری و ایمنی",
        text: "تمیزی دستگاه:",
        inspectionMethod: "عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی بدنه",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "تمیزی دستگاه: \nاطمینان از عاری بودن ژنراتور و دیزل از گرد و غبار زیاد، به خصوص در اطراف فیلترهای هوا، رادیاتور و اجزای الکتریکی.",
      },
      {
        code: '12-1-2',
        category: "وضعیت ظاهری و ایمنی",
        text: "نشت سیالات:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشت سیالات: \nبررسی چشمی تمام قسمت‌ها برای یافتن هرگونه نشتی روغن، مایع خنک‌کننده، یا سوخت.",
      },
      {
        code: '12-1-3',
        category: "وضعیت ظاهری و ایمنی",
        text: "اتصالات کابل‌ها:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "اتصالات کابل‌ها: \nاطمینان از سفتی و سالم بودن تمام اتصالات کابل‌های برق خروجی و ورودی، و همچنین اتصالات باتری",
      },
      {
        code: '12-1-4',
        category: "وضعیت ظاهری و ایمنی",
        text: "سیستم اطفاء حریق:",
        inspectionMethod: "یک عدد کپسول پودر و گاز",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سیستم اعلام و اطفاء حریق:\n اگر وجود دارد، از وضعیت آماده‌باش آن مطمئن شوید",
      },
      {
        code: '12-2-1',
        category: "سیستم خنک‌کننده",
        text: "سطح مایع خنک‌کننده :",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح مایع خنک‌کننده :\n در مخزن انبساط یا رادیاتور",
      },
      {
        code: '12-2-2',
        category: "سیستم خنک‌کننده",
        text: "وضعیت رادیاتور و فن:",
        inspectionMethod: "عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت رادیاتور و فن:\n اطمینان از تمیزی پره‌های رادیاتور (عدم گرفتگی با گرد و غبار) و چرخش صحیح و بدون صدای فن",
      },
      {
        code: '12-2-3',
        category: "سیستم خنک‌کننده",
        text: "شیلنگ‌ها و اتصالات:",
        inspectionMethod: "با دست",
        fieldType: 'manual_check',
        unit: null,
        threshold: null,
        detail: "شیلنگ‌ها و اتصالات: \nبررسی شیلنگ‌ها برای ترک، تورم یا نشتی، و سفتی بست‌ها",
      },
      {
        code: '12-3-1',
        category: "سیستم روان‌کاری",
        text: "سطح روغن موتور :",
        inspectionMethod: "چک گیج روغن",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح روغن موتور : \nبا استفاده از گیج، سطح روغن را چک کنید",
      },
      {
        code: '12-3-2',
        category: "سیستم روان‌کاری",
        text: "رنگ و شفافیت روغن:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "رنگ و شفافیت روغن:\n روغن باید شفاف و قهوه‌ای تیره باشد. اگر شیری رنگ (مخلوط با آب) یا سیاه و کدر است، نشان‌دهنده مشکل است",
      },
      {
        code: '12-3-3',
        category: "سیستم روان‌کاری",
        text: "نشتی از فیلتر روغن و کارتل:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشتی از فیلتر روغن و کارتل:\n بررسی اطراف این قطعات برای یافتن هرگونه نشتی",
      },
      {
        code: '12-4-1',
        category: "سیستم سوخت‌رسانی",
        text: "سطح سوخت در مخزن:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح سوخت در مخزن:\n اطمینان از کافی بودن سوخت برای مدت زمان کار مورد نیاز",
      },
      {
        code: '12-4-2',
        category: "سیستم سوخت‌رسانی",
        text: "نشتی سوخت:",
        inspectionMethod: "بررسی شیلنگ‌ها، اتصالات، پمپ سوخت و انژکتورها",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشتی سوخت: \nبررسی شیلنگ‌ها، اتصالات، پمپ سوخت و انژکتورها",
      },
      {
        code: '12-4-3',
        category: "سیستم سوخت‌رسانی",
        text: "وضعیت فیلترهای سوخت:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت فیلترهای سوخت: \nاگر فیلترها دارای نشانگر گرفتگی هستند، وضعیت آن‌ها را بررسی کنید",
      },
      {
        code: '12-5-1',
        category: "سیستم هوا",
        text: "وضعیت فیلتر هوا :",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "وضعیت فیلتر هوا : \nدر محیط معدن، فیلتر هوا بسیار سریع کثیف می‌شود. از نظر گرفتگی و کثیفی بیش از حد آن را بررسی کنید. در صورت نیاز، آن را تمیز یا تعویض کنید",
      },
      {
        code: '12-5-2',
        category: "سیستم هوا",
        text: "نشتی در لوله‌های هوای ورودی:",
        inspectionMethod: "اطمینان از عدم وجود ترک یا شل بودن اتصالات",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشتی در لوله‌های هوای ورودی: \nاطمینان از عدم وجود ترک یا شل بودن اتصالات",
      },
      {
        code: '12-6-1',
        category: "سیستم باتری",
        text: "سطح الکترولیت (در صورت امکان):",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "سطح الکترولیت (در صورت امکان): \nاگر باتری از نوع قابل شارژ با دسترسی به سلول‌ها است، سطح الکترولیت را چک کنید.",
      },
      {
        code: '12-6-2',
        category: "سیستم باتری",
        text: "ولتاژ باتری:",
        inspectionMethod: "با اهم مترباید حدود 12.6 ولت در حالت استراحت باشد",
        fieldType: 'voltage',
        unit: "ولت",
        threshold: "با اهم مترباید حدود 12.6 ولت در حالت استراحت باشد",
        detail: "ولتاژ باتری: \nدر صورت امکان، ولتاژ باتری را با ولت‌متر چک کنید (باید حدود 12.6 ولت در حالت استراحت باشد).",
      },
      {
        code: '12-7-1',
        category: "عملکرد ژنراتور",
        text: "صدای کارکرد:",
        inspectionMethod: "به صداهای غیرعادی موتور (مثل تق‌تق، سوت، کوبش)",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "صدای کارکرد: \nبه صداهای غیرعادی موتور (مثل تق‌تق، سوت، کوبش) و صدای خود ژنراتور گوش دهید",
      },
      {
        code: '12-7-2',
        category: "عملکرد ژنراتور",
        text: "لرزش:",
        inspectionMethod: "دستگاه ارتعاش سنج",
        fieldType: 'vibration',
        unit: null,
        threshold: null,
        detail: "لرزش:\n بررسی لرزش بیش از حد دستگاه در حین کار",
      },
      {
        code: '12-7-3',
        category: "عملکرد ژنراتور",
        text: "خروجی برق:",
        inspectionMethod: "با اهم متر",
        fieldType: 'voltage',
        unit: "ولت",
        threshold: null,
        detail: "خروجی برق: \nدر زمان کار، ولتاژ و فرکانس خروجی را با استفاده از مولتی‌متر یا نمایشگر دستگاه چک کنید و با مقادیر نرمال مقایسه کنید",
      },
      {
        code: '12-7-4',
        category: "عملکرد ژنراتور",
        text: "دمای ژنراتور:",
        inspectionMethod: "باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)",
        fieldType: 'temperature',
        unit: "سانتی‌گراد",
        threshold: "کمتر از دمای محیط + 40 درجه",
        detail: "دمای ژنراتور: \nدمای بدنه ژنراتور را (در صورت دسترسی) چک کنید",
      },
      {
        code: '12-8-1',
        category: "سیستم اگزوز",
        text: "نشتی اگزوز:",
        inspectionMethod: "بررسی منیفولد، لوله‌ها و اتصالات اگزوز برای یافتن نشتی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "نشتی اگزوز: \nبررسی منیفولد، لوله‌ها و اتصالات اگزوز برای یافتن نشتی.",
      },
      {
        code: '12-8-2',
        category: "سیستم اگزوز",
        text: "رنگ دود اگزوز:",
        inspectionMethod: "چشمی",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "رنگ دود اگزوز: \nدود سفید (نشانه آب در محفظه احتراق)، دود آبی (نشانه سوختن روغن) یا دود سیاه (نشانه احتراق ناقص یا گرفتگی فیلتر هوا) نیازمند بررسی فوری است",
      },
      {
        code: '12-9-1',
        category: "سیستم کنترل و نمایشگرها",
        text: "بررسی تمام نمایشگرها:",
        inspectionMethod: "فشار روغن، دمای آب، ولتاژ، فرکانس، آمپر خروجی",
        fieldType: 'amperage',
        unit: "آمپر",
        threshold: null,
        detail: "بررسی تمام نمایشگرها: \nفشار روغن، دمای آب، ولتاژ، فرکانس، آمپر خروجی، ساعت کارکرد. همه باید مقادیر نرمال را نشان دهند.",
      },
      {
        code: '12-9-2',
        category: "سیستم کنترل و نمایشگرها",
        text: "چراغ‌های هشدار:",
        inspectionMethod: "اطمینان از خاموش بودن تمام چراغ‌های هشدار دهنده",
        fieldType: 'visual',
        unit: null,
        threshold: null,
        detail: "چراغ‌های هشدار: \nاطمینان از خاموش بودن تمام چراغ‌های هشدار دهنده در حالت عادی کار",
      },
    ],
  },
]