-- داده اولیه (Seed) تجهیزات و چک‌لیست بازرسی
-- برگرفته از فایل واقعی «برنامه روزانه تعمیرات نگهداشت خط تولید» شرکت کی‌کاو آلتین

insert into equipment (code, name, inspection_frequency_days) values ('1', 'هاپر', 1);
insert into equipment (code, name, inspection_frequency_days) values ('2', 'نوار نقاله مادر', 7);
insert into equipment (code, name, inspection_frequency_days) values ('3', 'گریزلی', 7);
insert into equipment (code, name, inspection_frequency_days) values ('4', 'ترومل', 7);
insert into equipment (code, name, inspection_frequency_days) values ('5', 'سرند لرزان', 1);
insert into equipment (code, name, inspection_frequency_days) values ('6', 'پمپ اسلاری', 1);
insert into equipment (code, name, inspection_frequency_days) values ('7', 'مقسم‌ها', 7);
insert into equipment (code, name, inspection_frequency_days) values ('8', 'نلسون', 1);
insert into equipment (code, name, inspection_frequency_days) values ('9', 'اسلایدباکس', 7);
insert into equipment (code, name, inspection_frequency_days) values ('10', 'اسپیرال', 7);
insert into equipment (code, name, inspection_frequency_days) values ('11', 'نوار نقاله ماسه', 7);
insert into equipment (code, name, inspection_frequency_days) values ('12', 'دیزل ژنراتور', 1);

-- چک‌لیست هر تجهیز (با ارجاع به equipment بر اساس code)
do $$
declare
  eq_id uuid;
begin
  select id into eq_id from equipment where code = '1';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-1-1', 'موتور ویبره', 1, 'بررسی وزنه و تعادل :', 'بررسی چشمی هم راستا بودن و لرزش نامنظم', 'visual', NULL, NULL, 'بررسی وزن و تعادل :
بررسی چشمی اینکه آیا موتورهای ویبره با هم هم‌گام هستند یا یکی از آن‌ها صدای متفاوت یا لرزش نامنظم دارد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-1-2', 'موتور ویبره', 2, 'وضعیت اتصالات پایه :', 'شل بودن پیچ ها و واشر', 'visual', NULL, NULL, 'وضعیت اتصالات پایه : 
موتورهای ویبره با شدت زیاد به بدنه هاپر ضربه می‌زنند. بررسی کنید که پیچ‌های نگهدارنده موتور ویبره شل نشده باشند (این پیچ‌ها باید حتماً با واشر فنری یا مهره قفل‌کننده  بسته شده باشند');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-1-3', 'موتور ویبره', 3, 'بررسی سلامت پایه یا فنرهای ویبره :', 'دچار تغییر شکل نشده باشند', 'visual', NULL, NULL, 'بررسی سلامت پایه یا فنرهای ویبره : 
اگر موتورهای ویبره روی فنر یا پد لاستیکی سوار شده‌اند، بررسی کنید که پدها پاره نشده باشند یا فنرها دچار تغییر شکل نشوند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-1-4', 'موتور ویبره', 4, 'صدای برخورد فلز:', 'صدای فلز به فلز که نشانه شل شدن اتصالات هست', 'visual', NULL, NULL, 'صدای برخورد فلز:
 شنیدن صدای برخورد فلز به فلز  که نشان‌دهنده شل شدن یکی از اتصالات موتور به بدنه هاپر است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-1-5', 'موتور ویبره', 5, 'دمای موتور ویبره:', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'دمای موتور ویبره: 
موتورهای ویبره معمولاً گرم‌تر از موتورهای معمولی هستند، اما داغ شدن بیش از حد نشانه خرابی رولور  یا گیر کردن ذرات داخل آن است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-2-1', 'گیربکس', 6, 'سطح و سلامت روغن :', 'چک چشمی', 'visual', NULL, NULL, 'سطح و سلامت روغن :');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-2-2', 'گیربکس', 7, 'بررسی نشتی روغن :', 'چک کردن اطراف آب بندها', 'visual', NULL, NULL, 'بررسی وزن و تعادل :
بررسی چشمی اینکه آیا موتورهای ویبره با هم هم‌گام هستند یا یکی از آن‌ها صدای متفاوت یا لرزش نامنظم دارد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-2-3', 'گیربکس', 8, 'صدای چرخ‌دنده‌ها:', 'صدای زوزه نشانه عدم روغن کافی', 'visual', NULL, NULL, 'صدای برخورد فلز:
 شنیدن صدای برخورد فلز به فلز  که نشان‌دهنده شل شدن یکی از اتصالات موتور به بدنه هاپر است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-2-4', 'گیربکس', 9, 'بررسی خالی بودن کناره های الکترموتور فیدر از سنگ', 'چشمی', 'visual', NULL, NULL, 'بررسی خالی بودن کناره های الکترموتور فیدر از سنگ');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-2-5', 'گیربکس', 10, 'بررسی نشت روغن دینام', 'چشمی', 'visual', NULL, NULL, 'بررسی وزن و تعادل :
بررسی چشمی اینکه آیا موتورهای ویبره با هم هم‌گام هستند یا یکی از آن‌ها صدای متفاوت یا لرزش نامنظم دارد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '1-2-6', 'گیربکس', 11, 'تست آمپراژ (آمپرسنجی)  موتور اصلی :', 'با آمپر سنج', 'amperage', 'آمپر', NULL, 'چک‌لیست روزانه موتور ویبره');
  select id into eq_id from equipment where code = '2';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-1', NULL, 1, 'بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.', 'چشمی', 'visual', NULL, NULL, 'بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-2', NULL, 2, 'بررسی پارگی نوار', 'چشمی', 'visual', NULL, NULL, 'بررسی پارگی نوار');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-3-1', 'بررسی الکتروموتور', 3, 'بررسی دما ی الکتروموتور:', 'باید کمتر از دمای محیط + 40 سانتی گراد', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'بررسی دما ی الکتروموتور:
(داغ شدن بیش از حد معمول معمولاً نشانه بار بیش از حد، خرابی بلبرینگ‌ها یا کمبود تهویه است.)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-3-2', 'بررسی الکتروموتور', 4, 'بررسی صدا و لرزش الکتروموتور:', 'گوش دادن صدا زوزه، خش خش و لرزش غیرعادی', 'visual', NULL, NULL, 'بررسی صدا و لرزش الکتروموتور:
 (زوزه نشانه مشکلات در بلبرینگ یا گیربکس -تق‌تق یا ضربه نشانه خرابی در بخش کوپلینگ یا اتصال موتور به نوار نقاله- صدای خش‌خش: نشانه ورود گرد و غبار یا ذرات معدنی به داخل بدنه موتور-لرزش غیرعادی: اگر موتور یا پایه آن می‌لرزد، احتمالاً پیچ‌های پایه شل شده‌اند یا محور موتور دچار انحراف  شده است)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-3-3', 'بررسی الکتروموتور', 5, 'بازدید از پایه های الکتروموتور', 'چشمی', 'visual', NULL, NULL, 'بازدید از پایه های الکتروموتور');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-3-4', 'بررسی الکتروموتور', 6, 'فن خنک کننده الکتروموتور', 'تمیز بودن پره ها از گرد و غبار', 'visual', NULL, NULL, 'فن خنک کننده:
تمیزی پره‌های فن خنک‌کننده الکتروموتور که گرد و غبار حاصل از فرآوری  می‌تواند روی پره‌های فن موتور را بنشیند و جلوی خنک شدن را بگیرد. حتماً چک کنید که پره‌ها مسدود نشده باشند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-3-5', 'بررسی الکتروموتور', 7, 'وضعیت کابل‌های الکتروموتور', 'چشمی', 'visual', NULL, NULL, 'وضعیت کابل‌ها: 
بررسی کنید که کابل‌های برق موتور بر اثر لرزش نوار نقاله، آسیب ندیده یا از ترمینال‌ها شل نشده باشند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-4', NULL, 8, 'انحراف نوار :', 'چشمی از بالا', 'visual', NULL, NULL, 'انحراف نوار :
(اگر نوار به یک سمت متمایل شده باشد، فشار غیرعادی به بلبرینگ‌های موتور و رولیک‌ها وارد می‌شود و باعث می‌شود موتور زودتر از موعد داغ کند و بسوزد)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '2-5', NULL, 9, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :برای شناسایی افت کارایی یا نیم‌سوز شدن(اگر آمپر موتور ناگهان بالا رفته است، یعنی یا نوار نقاله گیر کرده، یا بار مواد روی نوار خیلی زیاد است، و یا موتور در حال سوختن (نیم‌سوز شدن) است)');
  select id into eq_id from equipment where code = '3';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-1', NULL, 1, 'بررسی صفحه فلزی شیبدار از لحاظ سالم بودن جوش ها', 'چشمی', 'visual', NULL, NULL, 'بررسی صفحه فلزی شیبدار از لحاظ سالم بودن جوش های کناره');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-2', NULL, 2, 'بررسی جوشهای توری', 'چشمی', 'visual', NULL, NULL, 'بررسی جوشهای توری ترومل');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-1', 'بررسی الکتروموتور:', 3, 'بررسی دمای بدنه، یاتاقان جلو و عقب  الکتروموتور:', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'بررسی دمای بدنه، یاتاقان جلو و عقب و باکس ترمینال الکتروموتور:
(اگر دما نسبت به حالت عادی ناگهانی بالا رفت، علامت بار اضافه، گیر مکانیکی، مشکل بلبرینگ یا بدی تهویه است)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-2', 'بررسی الکتروموتور:', 4, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):
 برای شناسایی افت کارایی یا نیم‌سوز شدن(آمپر هر سه فاز را کنترل کنید اختلاف زیاد بین فازها یا آمپر بالاتر از نرمال یعنی بار اضافی، مشکل در سیم پیچ گیرمکانیکی و ضعف برق ورودی)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-3', 'بررسی الکتروموتور:', 5, 'وضعیت ظاهری الکتروموتور:', 'عاری از گل و لای، ترک و شکستگی فن', 'visual', NULL, NULL, 'وضعیت ظاهری الکتروموتور:
 گل و لای، رطوبت ، ترک در بدنه و شکستگی فن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-4', 'بررسی الکتروموتور:', 6, 'فن خنک‌کننده الکتروموتور :', 'عاری از گل و لای، ترک و شکستگی فن', 'visual', NULL, NULL, 'فن خنک‌کننده الکتروموتور :
(مسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-5', 'بررسی الکتروموتور:', 7, 'پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.', 'با آچار', 'manual_check', NULL, NULL, 'پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-6', 'بررسی الکتروموتور:', 8, 'بوی غیرعادی الکتروموتور :', 'اعم از سوختگی ، بوی لاک و بوی روغن سوخته', 'visual', NULL, NULL, 'بوی غیرعادی الکتروموتور اعم از سوختگی ، بوی لاک و بوی روغن سوخته علامتی جدی می باشد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-3-7', 'بررسی الکتروموتور:', 9, 'وضعیت برق و ترمینال الکتروموتور:', 'شل نبودن کابل، نبود جرقه و عدم خوردگی و سولفاته', 'visual', NULL, NULL, 'وضعیت برق و ترمینال الکتروموتور:
 (شل نبودن کابل، داغ نبودن ترمینال، نبود جرقه، سالم بودن ارت و عدم خوردگی و سولفاته)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-4', NULL, 10, 'بررسی کن نلسون در هنگام پایان ران', 'چشمی', 'visual', NULL, NULL, 'بررسی کن نلسون در هنگام پایان ران');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-5', NULL, 11, 'بررسی تسمه ها از لحاظ پوسیدگی و پارگی', 'چشمی', 'visual', NULL, NULL, 'بررسی تسمه ها از لحاظ پوسیدگی و پارگی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-6-1', 'بررسی فنر:', 12, 'بررسی سلامت و وضعیت ظاهری فنرها  :', 'عدم کنده شدن و خمیدگی', 'visual', NULL, NULL, 'بررسی سلامت و وضعیت ظاهری فنرها (مهم‌ترین مورد) تغییر شکل : 
بررسی اینکه آیا فنرها هنوز حالت استاندارد خود را دارند یا به دلیل بار بیش از حد، “کنده” یا “خمیده” شده‌اند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-6-2', 'بررسی فنر:', 13, 'شکستگی یا ترک:', 'چشمی', 'visual', NULL, NULL, 'شکستگی یا ترک: 
بررسی دقیق ۸ عدد فنر برای یافتن هرگونه ترک یا شکستگی در بدنه فنر');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-6-3', 'بررسی فنر:', 14, 'تراز بودن ارتفاع فنرها:', 'لرزش غیرعادی درصورت بار اضافی در یکطرف', 'visual', NULL, NULL, 'تراز بودن ارتفاع:
 اگر یکی از فنرها بیش از بقیه فشرده شده باشد، یعنی بار روی گریزلی نامتقارن است (مثلاً مواد یک سمت گریزلی بیشتر از سمت دیگر می‌ریزد). این موضوع باعث لرزش غیرعادی و آسیب به شفت می‌شود.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-6-4', 'بررسی فنر:', 15, 'بررسی پیچ‌ها و مهره‌های اتصال فنر به شاسی:', 'عدم شل بودن پیچ و مهره فنر', 'visual', NULL, NULL, 'بررسی پیچ‌ها و مهره‌های اتصال فنر به شاسی(سفت بودن اتصالات: 
بررسی اینکه پیچ‌هایی که فنر را به شاسی یا به صفحه گریزلی متصل می‌کنند، بر اثر لرزش شل نشده باشند.-
نشانه خطر: اگر پیچ‌ها شل باشند، فنر شروع به “ضربه‌زدن”  می‌کند که صدای بسیار آزاردهنده‌ای دارد و می‌تواند باعث شکستن پایه گریزلی شود.)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-6-5', 'بررسی فنر:', 16, 'لرزش موتور:', 'با ارتغاش سنج', 'vibration', NULL, NULL, 'لرزش موتور: 
اگر فنرها درست نباشند، لرزش گریزلی به موتور گیربکس منتقل شده و باعث خرابی بلبرینگ‌های موتور می‌شود.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-7', NULL, 17, 'دمای گیربکس:', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'دمای گیربکس: 
چک کردن دمای گیربکس (همان‌طور که قبلاً گفته شد) برای اطمینان از اینکه لرزش‌های ناشی از خرابی فنرها به گیربکس آسیب نزده است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-8', NULL, 18, 'بررسی نازل آب از لحاظ گرفتگی', 'چشمی(عدم آبریزش )', 'visual', NULL, NULL, 'بررسی نازل آب از لحاظ گرفتگی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-9', NULL, 19, 'بررسی  جوشهای شوتی باطله', 'چشمی(عدم آبریزش )', 'visual', NULL, NULL, 'بررسی  جوشهای شوتی باطله');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-10', NULL, 20, 'بررسی جوشهای شوتی مواد معدنی', 'چشمی(عدم آبریزش )', 'visual', NULL, NULL, 'بررسی جوشهای شوتی مواد معدنی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '3-11', NULL, 21, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (18 کیلووات ):', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (18 کیلووات ) برای شناسایی افت کارایی یا نیم‌سوز شدن');
  select id into eq_id from equipment where code = '4';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-1', NULL, 1, 'صدای چرخش و یکنواختی حرکت:', 'با گوش دادن عدم تق تق، کوبش، و لرزش ضربه ای', 'visual', NULL, NULL, 'صدای چرخش و یکنواختی حرکت:
ترومل باید نرم و یکنواخت بچرخد، صدای غیرعادی مثل تق تق ، کوبش ، سایش فلز و لرزش ضربه ای باید فورا بررسی شود زیرا می تواند خرابی رولر یا تکیه گاه باشد یا کج شدن بدنه و یا  گیر کردن سنگ یا توده مواد داخل استوانه باشد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-2', NULL, 2, 'اطمینان از عدم گرفتگی  سوراخ‌ها برای شستشوی  نازل‌های آبپاش :', 'چشمی', 'visual', NULL, NULL, 'بررسی نازل‌های آبپاش :
اطمینان از گرفتگی نداشتن سوراخ‌ها برای شستشوی بهینه');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-3', NULL, 3, 'بازرسی زنجیر دوبل همیشه باید کمی روغنی باشد', 'اطمینان از روغن‌کاری کافی', 'visual', NULL, NULL, 'بازرسی زنجیر دوبل :
اطمینان از روغن‌کاری کافی اگر زنجیر خشک، شل یا ضربه‌زننده باشد، هم عمر زنجیر کم می‌شود هم به گیربکس فشار می‌آید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-4', NULL, 4, 'بررسی یاتاقان‌ها:', 'دما ، صدا، لقی غیر عادی و روغن ریزی و گریس ریزی', 'visual', NULL, NULL, 'بررسی یاتاقان‌ها:
دما ، صدا، لقی غیر عادی و روغن ریزی و گریس ریزی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-5', NULL, 5, 'بررسی وضعیت پوشش تفلون  :', 'چشمی پوشش تفلون سالم باشد', 'visual', NULL, NULL, 'بررسی وضعیت پوشش تفلون (حیاتی‌ترین مورد) :
بررسی ظاهری برای اطمینان از اینکه پوشش تفلون نشده یا کنده شده باشد، اگر تفلون پوشش‌دهی خود را از دست بدهد و زنجیر مستقیماً با بدنه فلزی توپی برخورد کند صدای بسیار شدیدی ایجاد می‌شود زنجیر به سرعت دندانه می‌خورد و پاره می‌شود و دندانه خورشیدی نیز خورده میشود');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-7', NULL, 6, 'هم‌راستایی  زنجیر و توپی:', 'عدم ضربه زدن زنجیر به توپی', 'visual', NULL, NULL, 'هم‌راستایی  زنجیر و توپی:
اگر زنجیر در یکی از بخش‌های مسیر خود صدا می‌دهد یا به سمت دیواره توپی برخورد می‌کند، یعنی تراز بودن  از بین رفته است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-8', NULL, 7, 'کشیدگی و سلامت زنجیر :', 'با دست شل یا سفت بودن زنجیر چک شود', 'manual_check', NULL, NULL, 'کشیدگی و سلامت زنجیر :
بررسی میزان شل بودن زنجیراگر زنجیر خیلی شل باشد: در هنگام حرکت، زنجیر روی دندانه‌های توپی پرش می‌کند  که باعث ضربه به موتور و شکستن دندانه‌ها می‌شود و اگر زنجیر خیلی سفت باشد: فشار غیرعادی به بلبرینگ‌های موتور و یاتاقان‌های توپی وارد می‌شود و باعث داغ شدن سریع آن‌ها می‌گردد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-9', NULL, 8, 'روغن کاری و گریس کاری زنجیر همیشه باید کمی روغنی باشد', 'چشمی', 'visual', NULL, NULL, 'زنجیر باید همیشه دارای لایه نازکی از روغن یا گریس مخصوص زنجیر باشد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-10-1', 'بررسی الکتروموتور 15 کیلو وات :', 9, 'بررسی الکتروموتورها از لحاظ روغن ریزی', 'چشمی', 'visual', NULL, NULL, 'بررسی الکتروموتورها از لحاظ روغن ریزی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-10-2', 'بررسی الکتروموتور 15 کیلو وات :', 10, 'بررسی دمای بدنه، یاتاقان جلو و عقب الکتروموتور', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'دمای بدنه : 
با استفاده از تف (در صورت مجاز بودن) یا ترجیحاً با یک ترمومتر لیزری، دمای کاسه بلبرینگ را چک کنید. دمای غیرعادی نشان‌دهنده اصطکاک زیاد یا نبود روان‌کاری است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-10-3', 'بررسی الکتروموتور 15 کیلو وات :', 11, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات )', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتوراصلی (۱۵ کیلووات ) برای شناسایی افت کارایی یا نیم‌سوز شدن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-10-4', 'بررسی الکتروموتور 15 کیلو وات :', 12, 'وضعیت ظاهری الکتروموتور', 'عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'وضعیت ظاهری الکتروموتور گل و لای، رطوبت ، ترک در بدنه و شکستگی فن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-10-5', 'بررسی الکتروموتور 15 کیلو وات :', 13, 'فن خنک‌کننده الکتروموتور', 'عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'فن خنک‌کننده الکتروموتور (مسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-11-1', 'بررسی شفت ترومل:', 14, 'دمای بدنه :', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'دمای بدنه : 
با استفاده از تف (در صورت مجاز بودن) یا ترجیحاً با یک ترمومتر لیزری، دمای کاسه بلبرینگ را چک کنید. دمای غیرعادی نشان‌دهنده اصطکاک زیاد یا نبود روان‌کاری است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-11-2', 'بررسی شفت ترومل:', 15, 'صدای غیرعادی :', 'صدای زوزه و تق تق نداشته باشد', 'visual', NULL, NULL, 'صدای غیرعادی : 
گوش دادن به صدای چرخش. هرگونه صدای «زوزه»  یا «تق‌تق»  نشان‌دهنده آسیب به رینگ‌های بلبرینگ یا عدم تراز شفت است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-11-3', 'بررسی شفت ترومل:', 16, 'لرزش محسوس :', 'با ارتعاش سنج', 'vibration', NULL, NULL, 'لرزش محسوس : 
بررسی  که آیا لرزش دستگاه در حد نرمال است یا لرزش‌های ضربه‌ای شنیده می‌شود.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-11-4', 'بررسی شفت ترومل:', 17, 'وضعیت روغن/گریس:', 'چشمی', 'visual', NULL, NULL, 'وضعیت روغن/گریس: 
اگر سیستم روغن‌کاری  دستی دارد، چک کنید که آیا نشتی از آب‌بند (Seal) کاسه بلبرینگ وجود دارد یا خیر');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-11-5', 'بررسی شفت ترومل:', 18, 'بررسی انحراف :', 'عدم نوسان زیاد', 'visual', NULL, NULL, 'بررسی انحراف :
 با چشم (در صورت امکان) یا سنسور، چک شود که آیا شفت در حین چرخش دارای لرزش‌های جانبی یا نوسان شدید است؟ (نوسان زیاد یعنی شفت کج شده یا بلبرینگ‌ها فاصله گرفته‌اند).');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-11-6', 'بررسی شفت ترومل:', 19, 'بررسی  پایه های نگهدارنده شفت ترومل', 'چشمی', 'visual', NULL, NULL, 'بررسی  پایه های نگهدارنده شفت ترومل');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-12', NULL, 20, 'بررسی جوشهای شوتی ترومل', 'چشمی', 'visual', NULL, NULL, 'بررسی جوشهای شوتی ترومل');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-13', NULL, 21, 'بررسی توری ترومل از لحاظ پارگی', 'چشمی', 'visual', NULL, NULL, 'بررسی توری ترومل از لحاظ پارگی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-14', NULL, 22, 'بررسی توری ترومل از لحاظ گرفتگی', 'چشمی', 'visual', NULL, NULL, 'بررسی توری ترومل از لحاظ گرفتگی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-15', NULL, 23, 'بررسی تسمه ها و پیچ و مهره های آن', 'لمسی', 'tactile', NULL, NULL, 'بررسی تسمه ها و پیچ و مهره های آن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '4-16', NULL, 24, 'تست آمپراژ (آمپرسنجی)  موتوراصلی (۱۵ کیلووات )', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتوراصلی (۱۵ کیلووات ) برای شناسایی افت کارایی یا نیم‌سوز شدن');
  select id into eq_id from equipment where code = '5';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-1', NULL, 1, 'بررسی پا اردکی ها از لحاظ گرفتگی', 'چشمی', 'visual', NULL, NULL, 'بررسی پا اردکی ها از لحاظ گرفتگی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-2', NULL, 2, 'بررسی کاشی های از لحاظ گرفتگی', 'چشمی', 'visual', NULL, NULL, 'بررسی کاشی های از لحاظ گرفتگی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-3', NULL, 3, 'بررسی پیچ و مهره های کاشی ها', 'لمسی', 'tactile', NULL, NULL, 'بررسی پیچ و مهره های کاشی ها');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-4', NULL, 4, 'بررسی عدم روغن ریزی موتور ویبره', 'چشمی', 'visual', NULL, NULL, 'بررسی عدم روغن ریزی موتور ویبره');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-5', NULL, 5, 'بررسی تراز بودن موتورها با میل گاردن(افقی و عمودی):', 'فاصله دو طرف کوپلینگ را اندازه بگیرید یکسان باشد', 'visual', NULL, NULL, 'بررسی تراز بودن موتورها با میل گاردن:
اگر موتورها به خوبی تراز نباشند، میل‌گاردن مثل یک میله کج شروع به ضربه زدن به شفت موتورها می‌کند و در کمتر از یک هفته بلبرینگ‌های موتور را خرد می‌کند');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-6', NULL, 6, 'کنترل زاویه میل گاردن:', 'بین 2 تا 5 درجه باید باشد', 'visual', NULL, 'بین 2 تا 5 درجه باید باشد', 'سلامت میل‌گاردن:
چون لرزش شدید است، هزارخاری‌ها یا کوپلینگ‌های میل‌گاردن مستعد ساییدگی هستند. روزانه چک کنید که در محل اتصال میل‌گاردن به موتور، لقی  ایجاد نشده باشد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-7', NULL, 7, 'پیچ‌های پایه موتور ویبره:', 'اطمینان از سفت بودن', 'visual', NULL, NULL, 'سفت بودن پیچ‌های پایه موتور ویبره:
اگر پیچ‌های پایه حتی کمی لق شوند، لرزش موتور باعث ضربه زدن به ورق فولادی زیر آن می‌شود که نتیجه‌اش شکستن شاسی یا ایجاد ترک در بدنه هاپر/سرند است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-8', NULL, 8, 'تست آمپراژ (آمپرسنجی)  موتورها :', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتورها برای شناسایی افت کارایی یا نیم‌سوز شدن(اگر وزنه‌های لنگ  داخل موتور ویبره بر اثر لرزش جابجا شوند یا بلبرینگ‌ها نیم‌سوز شوند، آمپر موتور ناگهان بالا می‌رود.)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-9', NULL, 9, 'صدای بلبرینگ‌های موتور ویبره:', 'صدای خشن نداشته باشد', 'visual', NULL, NULL, 'صدای بلبرینگ‌های موتور ویبره:
موتورهای ویبره تحت فشار “نیروی گریز از مرکز” شدیدی هستند. خرابی بلبرینگ در این موتورها معمولاً با صدای “هوم” خشن یا سوتِ ریز شروع می‌شود.استفاده از یک پیچ‌گوشتی بلند به عنوان “گوشی پزشکی” (دسته پیچ‌گوشتی را روی گوش و نوک آن را روی بدنه موتور بگذارید) تا صدای غیرعادی بلبرینگ را بهتر بشنوید)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-10', NULL, 10, 'داغ کردن بدنه موتور ویبره :', 'با دماسنج لیزری', 'temperature', 'سانتی‌گراد', NULL, 'داغ کردن بدنه موتور ویبره :
به دلیل نداشتن فن خنک‌کننده ، گرم می‌شوند. اما اگر دمای آن به قدری بالاست که دست را می‌سوزاند، یعنی موتور بیش از حد بار دارد یا بلبرینگ‌ها در حال گیرپاژ هستند');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-11', NULL, 11, 'بررسی ارتعاش وزنه‌ها:', 'با ارتعاش سنج', 'vibration', NULL, NULL, 'بررسی محافظ وزنه‌ها:
ارتعاش زیاد باعث شل شدن پیچ‌های  درپوش‌ها می‌شود. اگر درپوش بیفتد، وزنه‌های لنگ بیرون پرتاب می‌شوند که بسیار خطرناک است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '5-12', NULL, 12, 'سلامت میل‌گاردن:', 'عدم داشتن لقی و انحراف', 'visual', NULL, NULL, 'سلامت میل‌گاردن:
چون لرزش شدید است، هزارخاری‌ها یا کوپلینگ‌های میل‌گاردن مستعد ساییدگی هستند. روزانه چک کنید که در محل اتصال میل‌گاردن به موتور، لقی  ایجاد نشده باشد');
  select id into eq_id from equipment where code = '6';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-1-1', 'سیستم خنک‌کننده دیزل', 1, 'سطح مایع خنک‌کننده :', 'چک آب رادیاتور', 'visual', NULL, NULL, 'سطح مایع خنک‌کننده : 
در مخزن رادیاتور، مطمئن شوید که سطح مایع خنک‌کننده در حد نرمال است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-1-2', 'سیستم خنک‌کننده دیزل', 2, 'وضعیت شیلنگ‌ها و اتصالات :', 'عدم وجود نشتی، ترک یا ورم', 'visual', NULL, NULL, 'وضعیت شیلنگ‌ها و اتصالات : 
از نظر وجود نشتی، ترک‌خوردگی، یا ورم‌کردگی شیلنگ‌ها و همچنین سفتی اتصالات.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-1-3', 'سیستم خنک‌کننده دیزل', 3, 'عملکرد فن خنک‌کننده :', 'مطمئن شدن فن بدون صدای اضافی و با قدرت کافی می‌چرخد', 'visual', NULL, NULL, 'عملکرد فن خنک‌کننده : 
مطمئن شوید فن بدون صدای اضافی و با قدرت کافی می‌چرخد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-2-1', 'سیستم روان‌کاری دیزل', 4, 'سطح روغن موتور :', 'چشمی', 'visual', NULL, NULL, 'سطح روغن موتور : 
با گیج روغن، سطح آن را چک کنید. سطح باید بین حداقل و حداکثر علامت‌گذاری شده باشد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-2-2', 'سیستم روان‌کاری دیزل', 5, 'وضعیت فیلتر روغن :', 'عدم نشتی از فیلتر روغن', 'visual', NULL, NULL, 'وضعیت فیلتر روغن : 
بررسی کنید که آیا نشتی از اطراف فیلتر روغن وجود دارد یا خیر');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-2-3', 'سیستم روان‌کاری دیزل', 6, 'رنگ و بوی روغن:', 'عدم رنگ شیری و سیاه', 'visual', NULL, NULL, 'رنگ و بوی روغن: 
اگر امکانش هست، کمی روغن را بین انگشتان خود بمالید. رنگ غیرعادی (مثل شیری شدن که نشانه مخلوط شدن با آب است) یا بوی سوختگی نیاز به بررسی فوری دارد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-2-4', 'سیستم روان‌کاری دیزل', 7, 'بررسی عدم آب دهی سل مکانیکی پمپ اسلاری', 'چشمی', 'visual', NULL, NULL, 'بررسی عدم آب دهی سل مکانیکی پمپ اسلاری');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-3-1', 'سیستم سوخت‌رسانی دیزل', 8, 'سطح سوخت : بررسی مخزن سوخت', 'چشمی', 'visual', NULL, NULL, 'سطح سوخت : بررسی مخزن سوخت');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-3-2', 'سیستم سوخت‌رسانی دیزل', 9, 'نشتی سوخت :', 'از شیلنگ‌ها، اتصالات، پمپ گازوئیل، و اطراف انژکتورها', 'visual', NULL, NULL, 'نشتی سوخت : 
از شیلنگ‌ها، اتصالات، پمپ گازوئیل، و اطراف انژکتورها');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-3-3', 'سیستم سوخت‌رسانی دیزل', 10, 'نشتی اگزوز :', 'عدم دیدن دود سیاه یا آبی که از منیفولد، لوله‌ها و اتصالات', 'visual', NULL, NULL, 'نشتی اگزوز : 
از منیفولد، لوله‌ها و اتصالات. دود سیاه یا آبی که از اگزوز خارج می‌شود، می‌تواند نشانه مشکل باشد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-4-1', 'سیستم کلاچ چرخ‌دنده‌ای', 11, 'نشت گریس/روغن:', 'نشتی از محل کاسه نمدها نشانه خرابی آن‌هاست', 'visual', NULL, NULL, 'نشت گریس/روغن: 
 نشتی از محل کاسه نمدها (Seals) نشانه خرابی آن‌هاست.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-4-2', 'سیستم کلاچ چرخ‌دنده‌ای', 12, 'صدای غیرعادی:', 'عدم شنیدن صدای جیرجیر و تق تق', 'visual', NULL, NULL, 'صدای غیرعادی:
 در حین کار، به صداهای غیرعادی مثل «جیرجیر» یا «تق‌تق» گوش دهید که می‌تواند نشانه فرسودگی چرخ‌دنده‌ها یا عدم روان‌کاری باشد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-4-3', 'سیستم کلاچ چرخ‌دنده‌ای', 13, 'لرزش:', 'ارتعاش سنج', 'vibration', NULL, NULL, 'لرزش: 
لرزش بیش از حد در ناحیه اتصال کلاچ، نشان‌دهنده عدم تراز یا خرابی دندانه‌های چرخ‌دنده است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-5', NULL, 14, 'بررسی شل یا سفت بودن تسمه اسلاری', 'با آچار', 'manual_check', NULL, NULL, 'بررسی شل یا سفت بودن تسمه اسلاری');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-6-1', 'پمپ اسلاری:', 15, 'نشت از کاسه نمد پمپ :', 'چشمی', 'visual', NULL, NULL, 'نشت از کاسه نمد پمپ :
 این مهم‌ترین بخش پمپ است. هرگونه نشتی اسلاری از اطراف شفت پمپ نیاز به بررسی فوری دارد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-6-2', 'پمپ اسلاری:', 16, 'وضعیت روان‌کاری بلبرینگ پمپ:', 'با آچار', 'manual_check', NULL, NULL, 'وضعیت روان‌کاری بلبرینگ پمپ:
 اگر پمپ بلبرینگ جداگانه دارد، سطح گریس یا روغن آن را چک کنید.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-6-3', 'پمپ اسلاری:', 17, 'دمای بدنه پمپ:', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'دمای بدنه پمپ: 
با دست (با احتیاط) یا تف، دمای بدنه پمپ را چک کنید. داغ شدن بیش از حد معمولاً نشانه بار زیاد یا خرابی بلبرینگ پمپ است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-6-4', 'پمپ اسلاری:', 18, 'سفتی پیچ‌ها:', 'اطمینان از سفت بودن', 'visual', NULL, NULL, 'سفتی پیچ‌ها:
 تمامی پیچ‌های اتصال دهنده دیزل به پمپ، و اجزای نصب شده بر روی شاسی را از نظر سفتی چک کنید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '6-6-5', 'پمپ اسلاری:', 19, 'لوله های انتقال اسلاری:', 'عدم وجود ترک، پارگی، یا بادکردگی، مخصوصاً در نقاط اتصال', 'visual', NULL, NULL, 'لوله های انتقال اسلاری:
 از نظر وجود ترک، پارگی، یا بادکردگی، مخصوصاً در نقاط اتصال');
  select id into eq_id from equipment where code = '7';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '7-1', NULL, 1, 'بررسی ورق داخل مخزن از لحاظ پخش دوغاب بصورت یکسان', 'چشمی', 'visual', NULL, NULL, 'بررسی ورق داخل مخزن از لحاظ پخش دوغاب بصورت یکسان');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '7-2', NULL, 2, 'بررسی جوشهای مقسم', 'چشمی', 'visual', NULL, NULL, 'بررسی جوشهای مقسم');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '7-3', NULL, 3, 'بررسی جوشهای لوله های مقسم', 'چشمی', 'visual', NULL, NULL, 'بررسی جوشهای لوله های مقسم');
  select id into eq_id from equipment where code = '8';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-1', 'الکتروموتورها', 1, 'بررسی الکتروموتورها از لحاظ روغن ریزی', 'چشمی', 'visual', NULL, NULL, 'بررسی الکتروموتورها از لحاظ روغن ریزی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-2', 'الکتروموتورها', 2, 'بررسی دمای بدنه، یاتاقان جلو و عقب الکتروموتور:', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'بررسی دمای بدنه، یاتاقان جلو و عقب و باکس ترمینال الکتروموتور:
اگر دما نسبت به حالت عادی ناگهانی بالا رفت، علامت بار اضافه، گیر مکانیکی، مشکل بلبرینگ یا بدی تهویه است');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-3', 'الکتروموتورها', 3, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ):
 برای شناسایی افت کارایی یا نیم‌سوز شدن(آمپر هر سه فاز را کنترل کنید اختلاف زیاد بین فازها یا آمپر بالاتر از نرمال یعنی بار اضافی، مشکل در سیم پیچ گیرمکانیکی و ضعف برق ورودی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-4', 'الکتروموتورها', 4, 'وضعیت ظاهری الکتروموتور:', 'عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'وضعیت ظاهری الکتروموتور:
 گل و لای، رطوبت ، ترک در بدنه و شکستگی فن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-5', 'الکتروموتورها', 5, 'فن خنک‌کننده الکتروموتور :', 'عدم وجود گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'فن خنک‌کننده الکتروموتور :
مسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-6', 'الکتروموتورها', 6, 'پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.', 'با آچار', 'manual_check', NULL, NULL, 'پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-7', 'الکتروموتورها', 7, 'بوی غیرعادی الکتروموتور:', 'عدم وجود  سوختگی ، بوی لاک و بوی روغن سوخته', 'visual', NULL, NULL, 'بوی غیرعادی الکتروموتور:
 اعم از سوختگی ، بوی لاک و بوی روغن سوخته علامتی جدی می باشد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-1-8', 'الکتروموتورها', 8, 'وضعیت برق و ترمینال الکتروموتور:', 'شل نبودن کابل، نبود جرقه و عدم خوردگی و سولفاته', 'visual', NULL, NULL, 'وضعیت برق و ترمینال الکتروموتور:
 شل نبودن کابل، داغ نبودن ترمینال، نبود جرقه، سالم بودن ارت و عدم خوردگی و سولفاته');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-2', NULL, 9, 'بررسی کن نلسون در هنگام پایان ران', 'چشمی', 'visual', NULL, NULL, 'بررسی کن نلسون در هنگام پایان ران');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '8-3', NULL, 10, 'بررسی تسمه ها از لحاظ پوسیدگی و پارگی', 'چشمی', 'visual', NULL, NULL, 'بررسی تسمه ها از لحاظ پوسیدگی و پارگی');
  select id into eq_id from equipment where code = '9';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '9-1', NULL, 1, 'بررسی جوشهای باکس', 'چشمی', 'visual', NULL, NULL, 'بررسی جوشهای باکس');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '9-2', NULL, 2, 'بررسی خرابی چمن مصنوعی', 'چشمی', 'visual', NULL, NULL, 'بررسی خرابی چمن مصنوعی');
  select id into eq_id from equipment where code = '10';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-1-1', 'گیبرکس', 1, 'بررسی دمای بدنه (مهم‌ترین فاکتور):', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'بررسی دمای بدنه (مهم‌ترین فاکتور):
 با دماسنج لیزری(  دمای گیربکس در حین کار باید در محدوده نرمال (معمولاً زیر ۷۰-۸۰ درجه سانتی‌گراد) باشد. اگر دمای گیربکس ناگهان بالا رفته است، یا روغن کم شده، یا بار بیش از حد به آن تحمیل می‌شود (تنش در اسپیرال)، یا بلبرینگ‌ها در حال گیرپاژ هستند.)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-1-2', 'گیبرکس', 2, 'کنترل سطح روغن گیربکس (سطح‌سنج):', 'چشمی', 'visual', NULL, NULL, 'کنترل سطح روغن گیربکس (سطح‌سنج):
 سطح روغن نباید از خط نشان‌دهنده پایین‌تر برود. اگر سطح روغن کاهش یافته، بلافاصله باید محل نشت کاسه‌نمدها یا درزهای گیربکس پیدا شود');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-1-3', 'گیبرکس', 3, 'بررسی نشت روغن (نشتی‌گیری):', 'چشمی', 'visual', NULL, NULL, 'بررسی نشت روغن (نشتی‌گیری):
چک کردن زیر گیربکس و دور شفت‌ها (محل خروجی شفت به اسپیرال)گیربکس‌های قورباغه‌ای به دلیل لرزش شدید، مستعد نشت از کاسه‌نمد  هستند. اگر روغن نشت کند، به سرعت سطح روغن پایین آمده و چرخ‌دنده‌ها درگیر خشکی می‌شوند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-1-4', 'گیبرکس', 4, 'شنوایی  گیربکس(آنالیز صدای غیرعادی):', 'عدم صدای زوزه و تق تق', 'visual', NULL, NULL, 'شنوایی  گیربکس(آنالیز صدای غیرعادی):
گوش دادن به صدای گیربکس در حین کارصدای گیربکس باید یکنواخت باشد. شنیدن صدای “زوزه” شدید، “تق‌تق” یا صدای کوبش فلز با فلز، نشان‌دهنده خوردگی چرخ‌دنده‌ها  یا خرابی بلبرینگ‌های داخلی است');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-1-5', 'گیبرکس', 5, 'لرزش‌های غیرطبیعی گیربکس:', 'با ارتعاش سنج', 'vibration', NULL, NULL, 'لرزش‌های غیرطبیعی گیربکس:
 با دست گذاشتن روی بدنه گیربکس لرزش باید در حد معمولِ کاری باشد. اگر لرزش شدید و غیرمعمول حس می‌کنید، ممکن است محور اسپیرال با گیربکس هم‌راستا نباشد (هم راستا بودن مشکل پیدا کرده است) که فشار مضاعف به شفت خروجی گیربکس وارد می‌کند.اتصال موتور ۱۵ کیلووات به گیربکس را چک کنید. چون موتور ارتعاش دارد، اگر کوپلینگ یا واسطه بین موتور و گیربکس شل شده باشد، “لقی” ایجاد شده و دندانه‌های گیربکس خیلی سریع مستهلک می‌شوند');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-1', 'الکتروموتور', 6, 'بررسی الکتروموتورها از لحاظ روغن ریزی', 'چشمی', 'visual', NULL, NULL, 'بررسی الکتروموتورها از لحاظ روغن ریزی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-2', 'الکتروموتور', 7, 'بررسی دمای بدنه، یاتاقان جلو و عقب  الکتروموتور', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'الکتروموتور');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-3', 'الکتروموتور', 8, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ) :', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (۱۵ کیلووات ) :
برای شناسایی افت کارایی یا نیم‌سوز شدن(آمپر هر سه فاز را کنترل کنید اختلاف زیاد بین فازها یا آمپر بالاتر از نرمال یعنی بار اضافی، مشکل در سیم پیچ گیرمکانیکی و ضعف برق ورودی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-4', 'الکتروموتور', 9, 'وضعیت ظاهری الکتروموتور:', 'عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'وضعیت ظاهری الکتروموتور:
 گل و لای، رطوبت ، ترک در بدنه و شکستگی فن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-5', 'الکتروموتور', 10, 'فن خنک‌کننده الکتروموتور :', 'عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'فن خنک‌کننده الکتروموتور :
مسیر هوا نباید بسته باشد و اگر پره‌ها گل گرفته باشند، موتور سریع داغ می‌کند');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-6', 'الکتروموتور', 11, 'پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.', 'با آچار', 'manual_check', NULL, NULL, 'پیچ‌های پایه و فونداسیون الکتروموتور لقی نداشته باشد.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-7', 'الکتروموتور', 12, 'بوی غیرعادی الکتروموتور:', 'عدم سوختگی ، بوی لاک و بوی روغن سوخته', 'visual', NULL, NULL, 'بوی غیرعادی الکتروموتور:
 اعم از سوختگی ، بوی لاک و بوی روغن سوخته علامتی جدی می باشد');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-2-8', 'الکتروموتور', 13, 'وضعیت برق و ترمینال الکتروموتور:', 'شل نبودن کابل، نبود جرقه و عدم خوردگی و سولفاته', 'visual', NULL, NULL, 'وضعیت برق و ترمینال الکتروموتور:
 شل نبودن کابل، داغ نبودن ترمینال، نبود جرقه، سالم بودن ارت و عدم خوردگی و سولفاته');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '10-3', NULL, 14, 'بررسی جوشهای بدنه', 'چشمی', 'visual', NULL, NULL, 'بررسی جوشهای بدنه');
  select id into eq_id from equipment where code = '11';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-1', NULL, 1, 'بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.', 'چشمی', 'visual', NULL, NULL, 'بررسی وضعیت رولیک‌ها و اطمینان از حرکت روان آن‌ها.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-2', NULL, 2, 'بررسی پارگی نوار', 'چشمی', 'visual', NULL, NULL, 'بررسی پارگی نوار');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-3-1', 'بررسی الکتروموتور', 3, 'بررسی دما ی الکتروموتور:', 'با دماسنج لیزری', 'temperature', 'سانتی‌گراد', NULL, 'بررسی دما ی الکتروموتور:
داغ شدن بیش از حد معمول معمولاً نشانه بار بیش از حد، خرابی بلبرینگ‌ها یا کمبود تهویه است.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-3-2', 'بررسی الکتروموتور', 4, 'بررسی صدا و لرزش الکتروموتور:', 'عدم صدای زوزه و تق تق و لرزش بیش از حد', 'visual', NULL, NULL, 'بررسی صدا و لرزش الکتروموتور:
 زوزه نشانه مشکلات در بلبرینگ یا گیربکس -تق‌تق یا ضربه نشانه خرابی در بخش کوپلینگ یا اتصال موتور به نوار نقاله- صدای خش‌خش: نشانه ورود گرد و غبار یا ذرات معدنی به داخل بدنه موتور-لرزش غیرعادی: اگر موتور یا پایه آن می‌لرزد، احتمالاً پیچ‌های پایه شل شده‌اند یا محور موتور دچار انحراف  شده است');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-3-3', 'بررسی الکتروموتور', 5, 'بازدید از پایه های الکتروموتور', 'اطمینان از سفت بودن', 'visual', NULL, NULL, 'بازدید از پایه های الکتروموتور');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-3-4', 'بررسی الکتروموتور', 6, 'فن خنک کننده:', 'عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'فن خنک کننده:
تمیزی پره‌های فن خنک‌کننده الکتروموتور که گرد و غبار حاصل از فرآوری  می‌تواند روی پره‌های فن موتور را بنشیند و جلوی خنک شدن را بگیرد. حتماً چک کنید که پره‌ها مسدود نشده باشند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-4', NULL, 7, 'وضعیت کابل‌ها:', 'چشمی', 'visual', NULL, NULL, 'وضعیت کابل‌ها: 
بررسی کنید که کابل‌های برق موتور بر اثر لرزش نوار نقاله، آسیب ندیده یا از ترمینال‌ها شل نشده باشند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-5', NULL, 8, 'انحراف نوار :', 'چشمی', 'visual', NULL, NULL, 'انحراف نوار :
(اگر نوار به یک سمت متمایل شده باشد، فشار غیرعادی به بلبرینگ‌های موتور و رولیک‌ها وارد می‌شود و باعث می‌شود موتور زودتر از موعد داغ کند و بسوزد)');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '11-6', NULL, 9, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :', 'با آمپرسنج', 'amperage', 'آمپر', NULL, 'تست آمپراژ (آمپرسنجی)  موتور اصلی (7.5 کیلووات ) :
برای شناسایی افت کارایی یا نیم‌سوز شدن(اگر آمپر موتور ناگهان بالا رفته است، یعنی یا نوار نقاله گیر کرده، یا بار مواد روی نوار خیلی زیاد است، و یا موتور در حال سوختن (نیم‌سوز شدن) است');
  select id into eq_id from equipment where code = '12';
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-1-1', 'وضعیت ظاهری و ایمنی', 1, 'تمیزی دستگاه:', 'عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی بدنه', 'visual', NULL, NULL, 'تمیزی دستگاه: 
اطمینان از عاری بودن ژنراتور و دیزل از گرد و غبار زیاد، به خصوص در اطراف فیلترهای هوا، رادیاتور و اجزای الکتریکی.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-1-2', 'وضعیت ظاهری و ایمنی', 2, 'نشت سیالات:', 'چشمی', 'visual', NULL, NULL, 'نشت سیالات: 
بررسی چشمی تمام قسمت‌ها برای یافتن هرگونه نشتی روغن، مایع خنک‌کننده، یا سوخت.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-1-3', 'وضعیت ظاهری و ایمنی', 3, 'اتصالات کابل‌ها:', 'چشمی', 'visual', NULL, NULL, 'اتصالات کابل‌ها: 
اطمینان از سفتی و سالم بودن تمام اتصالات کابل‌های برق خروجی و ورودی، و همچنین اتصالات باتری');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-1-4', 'وضعیت ظاهری و ایمنی', 4, 'سیستم اطفاء حریق:', 'یک عدد کپسول پودر و گاز', 'visual', NULL, NULL, 'سیستم اعلام و اطفاء حریق:
 اگر وجود دارد، از وضعیت آماده‌باش آن مطمئن شوید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-2-1', 'سیستم خنک‌کننده', 5, 'سطح مایع خنک‌کننده :', 'چشمی', 'visual', NULL, NULL, 'سطح مایع خنک‌کننده :
 در مخزن انبساط یا رادیاتور');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-2-2', 'سیستم خنک‌کننده', 6, 'وضعیت رادیاتور و فن:', 'عدم  گل و لای، رطوبت ، ترک در بدنه و شکستگی فن', 'visual', NULL, NULL, 'وضعیت رادیاتور و فن:
 اطمینان از تمیزی پره‌های رادیاتور (عدم گرفتگی با گرد و غبار) و چرخش صحیح و بدون صدای فن');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-2-3', 'سیستم خنک‌کننده', 7, 'شیلنگ‌ها و اتصالات:', 'با دست', 'manual_check', NULL, NULL, 'شیلنگ‌ها و اتصالات: 
بررسی شیلنگ‌ها برای ترک، تورم یا نشتی، و سفتی بست‌ها');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-3-1', 'سیستم روان‌کاری', 8, 'سطح روغن موتور :', 'چک گیج روغن', 'visual', NULL, NULL, 'سطح روغن موتور : 
با استفاده از گیج، سطح روغن را چک کنید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-3-2', 'سیستم روان‌کاری', 9, 'رنگ و شفافیت روغن:', 'چشمی', 'visual', NULL, NULL, 'رنگ و شفافیت روغن:
 روغن باید شفاف و قهوه‌ای تیره باشد. اگر شیری رنگ (مخلوط با آب) یا سیاه و کدر است، نشان‌دهنده مشکل است');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-3-3', 'سیستم روان‌کاری', 10, 'نشتی از فیلتر روغن و کارتل:', 'چشمی', 'visual', NULL, NULL, 'نشتی از فیلتر روغن و کارتل:
 بررسی اطراف این قطعات برای یافتن هرگونه نشتی');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-4-1', 'سیستم سوخت‌رسانی', 11, 'سطح سوخت در مخزن:', 'چشمی', 'visual', NULL, NULL, 'سطح سوخت در مخزن:
 اطمینان از کافی بودن سوخت برای مدت زمان کار مورد نیاز');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-4-2', 'سیستم سوخت‌رسانی', 12, 'نشتی سوخت:', 'بررسی شیلنگ‌ها، اتصالات، پمپ سوخت و انژکتورها', 'visual', NULL, NULL, 'نشتی سوخت: 
بررسی شیلنگ‌ها، اتصالات، پمپ سوخت و انژکتورها');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-4-3', 'سیستم سوخت‌رسانی', 13, 'وضعیت فیلترهای سوخت:', 'چشمی', 'visual', NULL, NULL, 'وضعیت فیلترهای سوخت: 
اگر فیلترها دارای نشانگر گرفتگی هستند، وضعیت آن‌ها را بررسی کنید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-5-1', 'سیستم هوا', 14, 'وضعیت فیلتر هوا :', 'چشمی', 'visual', NULL, NULL, 'وضعیت فیلتر هوا : 
در محیط معدن، فیلتر هوا بسیار سریع کثیف می‌شود. از نظر گرفتگی و کثیفی بیش از حد آن را بررسی کنید. در صورت نیاز، آن را تمیز یا تعویض کنید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-5-2', 'سیستم هوا', 15, 'نشتی در لوله‌های هوای ورودی:', 'اطمینان از عدم وجود ترک یا شل بودن اتصالات', 'visual', NULL, NULL, 'نشتی در لوله‌های هوای ورودی: 
اطمینان از عدم وجود ترک یا شل بودن اتصالات');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-6-1', 'سیستم باتری', 16, 'سطح الکترولیت (در صورت امکان):', 'چشمی', 'visual', NULL, NULL, 'سطح الکترولیت (در صورت امکان): 
اگر باتری از نوع قابل شارژ با دسترسی به سلول‌ها است، سطح الکترولیت را چک کنید.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-6-2', 'سیستم باتری', 17, 'ولتاژ باتری:', 'با اهم مترباید حدود 12.6 ولت در حالت استراحت باشد', 'voltage', 'ولت', 'با اهم مترباید حدود 12.6 ولت در حالت استراحت باشد', 'ولتاژ باتری: 
در صورت امکان، ولتاژ باتری را با ولت‌متر چک کنید (باید حدود 12.6 ولت در حالت استراحت باشد).');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-7-1', 'عملکرد ژنراتور', 18, 'صدای کارکرد:', 'به صداهای غیرعادی موتور (مثل تق‌تق، سوت، کوبش)', 'visual', NULL, NULL, 'صدای کارکرد: 
به صداهای غیرعادی موتور (مثل تق‌تق، سوت، کوبش) و صدای خود ژنراتور گوش دهید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-7-2', 'عملکرد ژنراتور', 19, 'لرزش:', 'دستگاه ارتعاش سنج', 'vibration', NULL, NULL, 'لرزش:
 بررسی لرزش بیش از حد دستگاه در حین کار');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-7-3', 'عملکرد ژنراتور', 20, 'خروجی برق:', 'با اهم متر', 'voltage', 'ولت', NULL, 'خروجی برق: 
در زمان کار، ولتاژ و فرکانس خروجی را با استفاده از مولتی‌متر یا نمایشگر دستگاه چک کنید و با مقادیر نرمال مقایسه کنید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-7-4', 'عملکرد ژنراتور', 21, 'دمای ژنراتور:', 'باید کمتر از دمای محیط + 40 سانتی گراد(با دما سنج)', 'temperature', 'سانتی‌گراد', 'کمتر از دمای محیط + 40 درجه', 'دمای ژنراتور: 
دمای بدنه ژنراتور را (در صورت دسترسی) چک کنید');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-8-1', 'سیستم اگزوز', 22, 'نشتی اگزوز:', 'بررسی منیفولد، لوله‌ها و اتصالات اگزوز برای یافتن نشتی', 'visual', NULL, NULL, 'نشتی اگزوز: 
بررسی منیفولد، لوله‌ها و اتصالات اگزوز برای یافتن نشتی.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-8-2', 'سیستم اگزوز', 23, 'رنگ دود اگزوز:', 'چشمی', 'visual', NULL, NULL, 'رنگ دود اگزوز: 
دود سفید (نشانه آب در محفظه احتراق)، دود آبی (نشانه سوختن روغن) یا دود سیاه (نشانه احتراق ناقص یا گرفتگی فیلتر هوا) نیازمند بررسی فوری است');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-9-1', 'سیستم کنترل و نمایشگرها', 24, 'بررسی تمام نمایشگرها:', 'فشار روغن، دمای آب، ولتاژ، فرکانس، آمپر خروجی', 'amperage', 'آمپر', NULL, 'بررسی تمام نمایشگرها: 
فشار روغن، دمای آب، ولتاژ، فرکانس، آمپر خروجی، ساعت کارکرد. همه باید مقادیر نرمال را نشان دهند.');
  insert into inspection_checklist_items (equipment_id, code, category, item_order, item_text, inspection_method, field_type, unit, threshold_text, detail_text) values (eq_id, '12-9-2', 'سیستم کنترل و نمایشگرها', 25, 'چراغ‌های هشدار:', 'اطمینان از خاموش بودن تمام چراغ‌های هشدار دهنده', 'visual', NULL, NULL, 'چراغ‌های هشدار: 
اطمینان از خاموش بودن تمام چراغ‌های هشدار دهنده در حالت عادی کار');
end $$;